import { SiAdobeaftereffects, SiAdobeillustrator, SiAdobephotoshop, SiBlender, SiCss3, SiD3Dotjs, SiEthereum, SiFigma, SiFirebase, SiGithub, SiGraphql, SiHtml5, SiJavascript, SiNextdotjs, SiNodedotjs, SiOpengl, SiReact, SiSass, SiSocketdotio, SiSupabase, SiSvelte, SiTailwindcss, SiThreedotjs, SiTypescript, SiVercel, SiWebflow } from "react-icons/si";
import {TbCurrencySolana} from 'react-icons/tb'
export const iconComponentMap = {
    "Threejs": SiThreedotjs,
    "Blender": SiBlender,
    "Illustrator": SiAdobeillustrator,
    "Photoshop": SiAdobephotoshop,
    "After Effects": SiAdobeaftereffects,
    "Nextjs": SiNextdotjs,
    "Ethereum": SiEthereum,
    "Firebase": SiFirebase,
    "Graphql": SiGraphql,
    "Javascript": SiJavascript,
    "Typescript": SiTypescript,
    "Css": SiCss3,
    "Html": SiHtml5,
    "Tailwind css": SiTailwindcss,
    "Nodejs": SiNodedotjs,
    "Opengl": SiOpengl,
    "Figma": SiFigma,
    "Vercel": SiVercel,
    "React": SiReact,
    "Github": SiGithub,
    "Socketio": SiSocketdotio,
    "D3.js": SiD3Dotjs,
    'Svelte': SiSvelte,
    "Supabase": SiSupabase,
    "Sass" : SiSass,
    "Webflow": SiWebflow,
    "Ethers": SiEthereum,
    "glsl": SiOpengl,
    'Solana web3js': TbCurrencySolana
  };