/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import * as THREE from "three";
import React, { useEffect, useRef } from "react";
import { useFrame, useThree } from "@react-three/fiber";
import { useGLTF, PerspectiveCamera, useAnimations, Html } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { useScroll, useTransform } from "framer-motion";
import useCharacterStore from "@/lib/zustandStore";
import { useState } from "react";
import "../../globals.css"
type GLTFResult = GLTF & {
  nodes: {
    ["GEO-rain_eyebrows"]: THREE.SkinnedMesh;
    ["GEO-rain_eyelashes"]: THREE.SkinnedMesh;
    ["GEO-rain_gums_lower_Data"]: THREE.SkinnedMesh;
    ["GEO-rain_gums_lower_Data_1"]: THREE.SkinnedMesh;
    ["GEO-rain_gums_upper_Data"]: THREE.SkinnedMesh;
    ["GEO-rain_gums_upper_Data_1"]: THREE.SkinnedMesh;
    ["GEO-rain_tongue"]: THREE.SkinnedMesh;
    ["GEO-rain_body"]: THREE.SkinnedMesh;
    ["GEO-rain_body001"]: THREE.SkinnedMesh;
    ["GEO-rain_shoes_Data"]: THREE.SkinnedMesh;
    ["GEO-rain_shoes_Data_1"]: THREE.SkinnedMesh;
    ["GEO-rain_shoes_Data_2"]: THREE.SkinnedMesh;
    ["GEO-rain_shoes_Data_3"]: THREE.SkinnedMesh;
    ["GEO-rain_top"]: THREE.SkinnedMesh;
    ["GEO-rain_eyes"]: THREE.SkinnedMesh;
    ["GEO-rain_head"]: THREE.SkinnedMesh;
    ["GEO-rain_hair_main"]: THREE.SkinnedMesh;
    ["GEO-rain_hair_ponytail"]: THREE.SkinnedMesh;
    ["GEO-rain_hair_strand"]: THREE.SkinnedMesh;
    ["GEO-rain_jeans"]: THREE.SkinnedMesh;
    Cylinder: THREE.Mesh;
    Cylinder001: THREE.Mesh;
    TeethT: THREE.Bone;
    TeethB: THREE.Bone;
    ["P-BB-ChinM"]: THREE.Bone;
    ["P-GRP-Lip_TopM"]: THREE.Bone;
    ["P-BB-Chin_2L"]: THREE.Bone;
    ["P-BB-LaughLineM"]: THREE.Bone;
    ["P-BB-LaughLine_7L"]: THREE.Bone;
    ["P-GRP-Lip_BotM"]: THREE.Bone;
    ["FK-ToeL"]: THREE.Bone;
    ["DEF-COR-Shin_TopL"]: THREE.Bone;
    ["GRAB-HandL"]: THREE.Bone;
    ["P-BB-JawLine_3L"]: THREE.Bone;
    ["P-BB-Nose_3M"]: THREE.Bone;
    ["P-BB-Cheek_SneerL"]: THREE.Bone;
    ["P-BB-Cheek_3_2L"]: THREE.Bone;
    ["P-BB-Cheek_2_2L"]: THREE.Bone;
    ["P-BB-LaughLine_2L"]: THREE.Bone;
    ["P-BB-Nostril_2L"]: THREE.Bone;
    ["P-BB-Nostril_1L"]: THREE.Bone;
    ["P-BB-LaughLine_1L"]: THREE.Bone;
    ["P-BB-LaughLine_6L"]: THREE.Bone;
    ["P-BB-LaughLine_4L"]: THREE.Bone;
    ["P-BB-Cheek_2_1L"]: THREE.Bone;
    ["P-BB-Cheek_3_1L"]: THREE.Bone;
    ["P-BB-JawLine_2L"]: THREE.Bone;
    ["P-BB-LaughLine_5L"]: THREE.Bone;
    ["P-BB-Cheek_1_2L"]: THREE.Bone;
    ["P-BB-Cheek_4_2L"]: THREE.Bone;
    ["P-BB-Cheek_1_1L"]: THREE.Bone;
    ["P-GRP-Nose_Front"]: THREE.Bone;
    ["P-GRP-Lip_Top_1L"]: THREE.Bone;
    ["P-GRP-Lip_Bot_1L"]: THREE.Bone;
    Tongue_Root: THREE.Bone;
    ["N-BB-Eyelid_Top_1L"]: THREE.Bone;
    ["N-TAN-Tail-Crease_Lid_Across_1L"]: THREE.Bone;
    ["N-BB-Cheek_SneerL"]: THREE.Bone;
    ["N-TAN-FaceRing_4L"]: THREE.Bone;
    ["N-BB-Cheek_2_1L"]: THREE.Bone;
    ["N-TAN-FaceRing_5L"]: THREE.Bone;
    ["N-BB-Eyelid_Bot_5L"]: THREE.Bone;
    ["N-TAN-Cheek_4_0L"]: THREE.Bone;
    ["N-BB-EyeLid_Crease_9L"]: THREE.Bone;
    ["N-TAN-Cheek_4_1L"]: THREE.Bone;
    ["N-TAN-Eyelid_Top_1L"]: THREE.Bone;
    ["N-BB-Eyelid_Bot_1L"]: THREE.Bone;
    ["N-TAN-Eyelid_Bot_1L"]: THREE.Bone;
    ["N-TAN-Tail-Eyelid_Bot_4L"]: THREE.Bone;
    ["N-BB-EyeLid_Crease_7L"]: THREE.Bone;
    ["N-TAN-Cheek_2_1L"]: THREE.Bone;
    ["N-TAN-Cheek_2_2L"]: THREE.Bone;
    ["N-TAN-NoseCrease_2L"]: THREE.Bone;
    ["N-TAN-EyeLid_Crease_7L"]: THREE.Bone;
    ["N-TAN-EyeLid_Crease_9L"]: THREE.Bone;
    ["N-BB-Lip_Bot_CornerL"]: THREE.Bone;
    ["N-TAN-Tail-Lip_Bot_Bot_2L"]: THREE.Bone;
    ["N-TAN-Tail-Lip_Bot_Top_2L"]: THREE.Bone;
    ["N-BB-Lip_Top_CornerL"]: THREE.Bone;
    ["N-TAN-Lip_Top_Top_2L"]: THREE.Bone;
    ["N-TAN-Lip_Top_Bot_2L"]: THREE.Bone;
    ["N-TAN-LaughLine_Lip_Across_1L"]: THREE.Bone;
    ["N-TAN-Tail-LaughLine_Cheek_Across_1_2L"]: THREE.Bone;
    ["N-TAN-LaughLine_Lip_Across_2L"]: THREE.Bone;
    ROOT: THREE.Bone;
    ["HNG-ThighL"]: THREE.Bone;
    ["HNG-Upperarm_ParentL"]: THREE.Bone;
    ["CTR-COR-Thumb_1L"]: THREE.Bone;
    ["TGT-Eyes"]: THREE.Bone;
    ["P-FK-Head"]: THREE.Bone;
    ["P-GRP-Lip_Bot_2L"]: THREE.Bone;
    ["P-GRP-Lip_Bot_2R"]: THREE.Bone;
    ["P-GRP-Lip_Top_2L"]: THREE.Bone;
    ["P-GRP-Lip_Top_2R"]: THREE.Bone;
    ["P-ACT-Lips_CornerL"]: THREE.Bone;
    ["P-ACT-Lips_CornerR"]: THREE.Bone;
    ["P-BB-Cheek_4_1L"]: THREE.Bone;
    ["P-BB-JawLine_1L"]: THREE.Bone;
    ["P-GRP-NostrilL"]: THREE.Bone;
    ["P-BB-Forehead-_TopM"]: THREE.Bone;
    ["GRP-Nose_Bridge2"]: THREE.Bone;
    ["P-BB-Forehead-_Top_1L"]: THREE.Bone;
    ["P-BB-Forehead-_Top_3L"]: THREE.Bone;
    ["P-BB-Forehead-_Top_2L"]: THREE.Bone;
    ["P-BB-Forehead-_1L"]: THREE.Bone;
    ["P-FK-Neck"]: THREE.Bone;
    ["P-BB-Chin_2R"]: THREE.Bone;
    ["P-BB-LaughLine_7R"]: THREE.Bone;
    ["P-BB-JawLine_3R"]: THREE.Bone;
    ["P-BB-Cheek_SneerR"]: THREE.Bone;
    ["P-BB-Cheek_3_2R"]: THREE.Bone;
    ["P-BB-Cheek_2_2R"]: THREE.Bone;
    ["P-BB-LaughLine_2R"]: THREE.Bone;
    ["P-BB-Nostril_2R"]: THREE.Bone;
    ["P-BB-Nostril_1R"]: THREE.Bone;
    ["P-BB-LaughLine_1R"]: THREE.Bone;
    ["P-BB-LaughLine_6R"]: THREE.Bone;
    ["P-BB-LaughLine_4R"]: THREE.Bone;
    ["P-BB-Cheek_2_1R"]: THREE.Bone;
    ["P-BB-Cheek_3_1R"]: THREE.Bone;
    ["P-BB-JawLine_2R"]: THREE.Bone;
    ["P-BB-LaughLine_5R"]: THREE.Bone;
    ["P-BB-Cheek_1_2R"]: THREE.Bone;
    ["P-BB-Cheek_4_2R"]: THREE.Bone;
    ["P-BB-Cheek_1_1R"]: THREE.Bone;
    ["P-GRP-Lip_Top_1R"]: THREE.Bone;
    ["P-GRP-Lip_Bot_1R"]: THREE.Bone;
    ["N-BB-Eyelid_Top_1R"]: THREE.Bone;
    ["N-TAN-Tail-Crease_Lid_Across_1R"]: THREE.Bone;
    ["N-BB-Cheek_SneerR"]: THREE.Bone;
    ["N-TAN-FaceRing_4R"]: THREE.Bone;
    ["N-BB-Cheek_2_1R"]: THREE.Bone;
    ["N-TAN-FaceRing_5R"]: THREE.Bone;
    ["N-BB-Eyelid_Bot_5R"]: THREE.Bone;
    ["N-TAN-Cheek_4_0R"]: THREE.Bone;
    ["N-BB-EyeLid_Crease_9R"]: THREE.Bone;
    ["N-TAN-Cheek_4_1R"]: THREE.Bone;
    ["N-TAN-Eyelid_Top_1R"]: THREE.Bone;
    ["N-BB-Eyelid_Bot_1R"]: THREE.Bone;
    ["N-TAN-Eyelid_Bot_1R"]: THREE.Bone;
    ["N-TAN-Tail-Eyelid_Bot_4R"]: THREE.Bone;
    ["N-BB-EyeLid_Crease_7R"]: THREE.Bone;
    ["N-TAN-Cheek_2_1R"]: THREE.Bone;
    ["N-TAN-Cheek_2_2R"]: THREE.Bone;
    ["N-BB-EyeLid_Crease_6R"]: THREE.Bone;
    ["N-TAN-NoseCrease_1R"]: THREE.Bone;
    ["N-TAN-NoseCrease_2R"]: THREE.Bone;
    ["N-TAN-EyeLid_Crease_6R"]: THREE.Bone;
    ["N-TAN-EyeLid_Crease_7R"]: THREE.Bone;
    ["N-TAN-EyeLid_Crease_9R"]: THREE.Bone;
    ["N-BB-Lip_Bot_CornerR"]: THREE.Bone;
    ["N-TAN-Tail-Lip_Bot_Bot_2R"]: THREE.Bone;
    ["N-TAN-Tail-Lip_Bot_Top_2R"]: THREE.Bone;
    ["N-BB-Lip_Top_CornerR"]: THREE.Bone;
    ["N-TAN-Lip_Top_Top_2R"]: THREE.Bone;
    ["N-TAN-Lip_Top_Bot_2R"]: THREE.Bone;
    ["N-TAN-LaughLine_Lip_Across_1R"]: THREE.Bone;
    ["N-TAN-Tail-LaughLine_Cheek_Across_1_2R"]: THREE.Bone;
    ["N-TAN-LaughLine_Lip_Across_2R"]: THREE.Bone;
    ["P-BB-Cheek_4_1R"]: THREE.Bone;
    ["P-BB-JawLine_1R"]: THREE.Bone;
    ["P-GRP-NostrilR"]: THREE.Bone;
    ["P-BB-Forehead-_Top_1R"]: THREE.Bone;
    ["P-BB-Forehead-_Top_3R"]: THREE.Bone;
    ["P-BB-Forehead-_Top_2R"]: THREE.Bone;
    ["P-BB-Forehead-_1R"]: THREE.Bone;
    ["P-GRP-Nose_Bridge"]: THREE.Bone;
    ["CTR-COR-Thumb_2L"]: THREE.Bone;
    ["GRP-STR-Nose_Front"]: THREE.Bone;
    ["GRP-STR-NostrilL"]: THREE.Bone;
    ["GRP-STR-NostrilR"]: THREE.Bone;
    ["P-SK-Cheek_PuffL"]: THREE.Bone;
    ["P-SK-Cheek_PuffR"]: THREE.Bone;
    ["FK-ToeR"]: THREE.Bone;
    ["DEF-COR-Shin_TopR"]: THREE.Bone;
    ["GRAB-HandR"]: THREE.Bone;
    ["HNG-ThighR"]: THREE.Bone;
    ["HNG-Upperarm_ParentR"]: THREE.Bone;
    ["CTR-COR-Thumb_1R"]: THREE.Bone;
    ["CTR-COR-Thumb_2R"]: THREE.Bone;
    Root_EarL: THREE.Bone;
    Root_EarR: THREE.Bone;
    ["IK-P-Pole-ShinL"]: THREE.Bone;
    ["IK-P-Pole-ShinR"]: THREE.Bone;
    ["N-BB-Forehead-_TopM"]: THREE.Bone;
    ["N-TAN-Forehead_2M"]: THREE.Bone;
    ["N-BB-Eyebrow_TopM"]: THREE.Bone;
    ["N-TAN-Eyebrow_AcrossM"]: THREE.Bone;
    ["N-BB-Eyebrow_BotM"]: THREE.Bone;
    ["N-TAN-Nose_1M"]: THREE.Bone;
    ["N-BB-Nose_1M"]: THREE.Bone;
    ["N-TAN-Nose_2M"]: THREE.Bone;
    ["N-BB-Nose_2M"]: THREE.Bone;
    ["N-TAN-Nose_3M"]: THREE.Bone;
    ["N-BB-Nose_3M"]: THREE.Bone;
    ["N-TAN-Nose_4M"]: THREE.Bone;
    ["N-BB-Nose_4M"]: THREE.Bone;
    ["N-TAN-Nose_5M"]: THREE.Bone;
    ["N-BB-Lip_Top_TopM"]: THREE.Bone;
    ["N-TAN-Lip_Top_AcrossM"]: THREE.Bone;
    ["N-BB-Lip_Top_BotM"]: THREE.Bone;
    ["N-TAN-Tail-Lip_Top_AcrossM"]: THREE.Bone;
    ["N-BB-LaughLine_3L"]: THREE.Bone;
    ["N-TAN-NoseRing_3L"]: THREE.Bone;
    ["N-BB-LaughLine_2L"]: THREE.Bone;
    ["N-TAN-NoseRing_4L"]: THREE.Bone;
    ["N-BB-LaughLine_1L"]: THREE.Bone;
    ["N-TAN-NoseRing_5L"]: THREE.Bone;
    ["N-TAN-Tail-NoseRing_5L"]: THREE.Bone;
    ["N-TAN-NoseFront_1L"]: THREE.Bone;
    ["N-BB-Nostril_1L"]: THREE.Bone;
    ["N-TAN-NoseFront_2L"]: THREE.Bone;
    ["N-TAN-Tail-NoseFront_2L"]: THREE.Bone;
    ["N-BB-Forehead-_Top_1L"]: THREE.Bone;
    ["N-TAN-Forehead_2_2L"]: THREE.Bone;
    ["N-BB-Eyebrow_Top_1L"]: THREE.Bone;
    ["N-TAN-Eyebrow_Across_1L"]: THREE.Bone;
    ["N-BB-Eyebrow_Bot_1L"]: THREE.Bone;
    ["N-TAN-Brow_Crease_Across_2L"]: THREE.Bone;
    ["N-BB-EyeLid_Crease_2L"]: THREE.Bone;
    ["N-TAN-Crease_Lid_Across_2L"]: THREE.Bone;
    ["N-BB-Eyelid_Top_2L"]: THREE.Bone;
    ["N-TAN-Tail-Crease_Lid_Across_2L"]: THREE.Bone;
    ["N-BB-Forehead-_1L"]: THREE.Bone;
    ["N-TAN-Forehead_1_2L"]: THREE.Bone;
    ["N-BB-Eyebrow_1L"]: THREE.Bone;
    ["N-TAN-Brow_Crease_Across_1L"]: THREE.Bone;
    ["N-BB-EyeLid_Crease_1L"]: THREE.Bone;
    ["N-TAN-Crease_Lid_Across_1L"]: THREE.Bone;
    ["N-BB-Forehead-_Top_3L"]: THREE.Bone;
    ["N-TAN-Forehead_4_2L"]: THREE.Bone;
    ["N-BB-Eyebrow_Top_3L"]: THREE.Bone;
    ["N-TAN-Eyebrow_Across_3L"]: THREE.Bone;
    ["N-BB-Eyebrow_Bot_3L"]: THREE.Bone;
    ["N-TAN-FaceRing_1L"]: THREE.Bone;
    ["N-BB-NoseBridge_1L"]: THREE.Bone;
    ["N-TAN-FaceRing_2L"]: THREE.Bone;
    ["N-BB-NoseBridge_2L"]: THREE.Bone;
    ["N-TAN-FaceRing_3L"]: THREE.Bone;
    ["N-BB-Cheek_3_1L"]: THREE.Bone;
    ["N-TAN-FaceRing_6L"]: THREE.Bone;
    ["N-BB-Cheek_4_1L"]: THREE.Bone;
    ["N-TAN-FaceRing_7L"]: THREE.Bone;
    ["N-BB-Cheek_5_1L"]: THREE.Bone;
    ["N-TAN-FaceRing_8L"]: THREE.Bone;
    ["N-TAN-Eyebrow_Upper_1L"]: THREE.Bone;
    ["N-TAN-Eyebrow_Upper_2L"]: THREE.Bone;
    ["N-BB-Eyebrow_Top_2L"]: THREE.Bone;
    ["N-TAN-Eyebrow_Upper_3L"]: THREE.Bone;
    ["N-TAN-Eyebrow_Upper_4L"]: THREE.Bone;
    ["N-TAN-Tail-Eyebrow_Upper_4L"]: THREE.Bone;
    ["N-TAN-Brow_Crease_Across_4L"]: THREE.Bone;
    ["N-BB-EyeLid_Crease_4L"]: THREE.Bone;
    ["N-TAN-Crease_Lid_Across_4L"]: THREE.Bone;
    ["N-BB-Eyelid_Top_4L"]: THREE.Bone;
    ["N-TAN-Tail-Crease_Lid_Across_4L"]: THREE.Bone;
    ["N-BB-Forehead-_Top_2L"]: THREE.Bone;
    ["N-TAN-Forehead_3_2L"]: THREE.Bone;
    ["N-TAN-Eyebrow_Across_2L"]: THREE.Bone;
    ["N-BB-Eyebrow_Bot_2L"]: THREE.Bone;
    ["N-TAN-Brow_Crease_Across_3L"]: THREE.Bone;
    ["N-BB-EyeLid_Crease_3L"]: THREE.Bone;
    ["N-TAN-Crease_Lid_Across_3L"]: THREE.Bone;
    ["N-BB-Eyelid_Top_3L"]: THREE.Bone;
    ["N-TAN-Tail-Crease_Lid_Across_3L"]: THREE.Bone;
    ["N-BB-TempleL"]: THREE.Bone;
    ["N-TAN-Temple_2L"]: THREE.Bone;
    ["N-BB-JawLine_1L"]: THREE.Bone;
    ["N-TAN-JawLine_1L"]: THREE.Bone;
    ["N-BB-JawLine_2L"]: THREE.Bone;
    ["N-TAN-JawLine_2L"]: THREE.Bone;
    ["N-BB-JawLine_3L"]: THREE.Bone;
    ["N-TAN-JawLine_3L"]: THREE.Bone;
    ["N-BB-JawLine_4L"]: THREE.Bone;
    ["N-TAN-JawLine_4L"]: THREE.Bone;
    ["N-BB-JawLine_5L"]: THREE.Bone;
    ["N-TAN-JawLine_5L"]: THREE.Bone;
    ["N-BB-JawLineM"]: THREE.Bone;
    ["N-TAN-Tail-JawLine_5L"]: THREE.Bone;
    ["N-TAN-Cheek_Jawline_Across_1L"]: THREE.Bone;
    ["N-TAN-Tail-Cheek_Jawline_Across_1L"]: THREE.Bone;
    ["N-TAN-Eyelid_Top_2L"]: THREE.Bone;
    ["N-TAN-Eyelid_Top_3L"]: THREE.Bone;
    ["N-TAN-Eyelid_Top_4L"]: THREE.Bone;
    ["N-BB-Eyelid_Top_5L"]: THREE.Bone;
    ["N-TAN-Tail-Eyelid_Top_4L"]: THREE.Bone;
    ["N-BB-Eyelid_Bot_2L"]: THREE.Bone;
    ["N-TAN-Eyelid_Bot_2L"]: THREE.Bone;
    ["N-BB-Eyelid_Bot_3L"]: THREE.Bone;
    ["N-TAN-Eyelid_Bot_3L"]: THREE.Bone;
    ["N-BB-Eyelid_Bot_4L"]: THREE.Bone;
    ["N-TAN-Eyelid_Bot_4L"]: THREE.Bone;
    ["N-BB-EyeLid_Crease_5L"]: THREE.Bone;
    ["N-TAN-NoseBridge_2_2L"]: THREE.Bone;
    ["N-TAN-NoseBridge_2_3L"]: THREE.Bone;
    ["N-TAN-Tail-NoseBridge_2_3L"]: THREE.Bone;
    ["N-TAN-NoseMidLine_3L"]: THREE.Bone;
    ["N-TAN-NoseMidLine_2L"]: THREE.Bone;
    ["N-TAN-NoseMidLine_1L"]: THREE.Bone;
    ["N-BB-Lip_Top_TopL"]: THREE.Bone;
    ["N-TAN-Lip_Top_AcrossL"]: THREE.Bone;
    ["N-BB-Lip_Top_BotL"]: THREE.Bone;
    ["N-TAN-Tail-Lip_Top_AcrossL"]: THREE.Bone;
    ["N-TAN-Cheek_2_0L"]: THREE.Bone;
    ["N-BB-Cheek_2_2L"]: THREE.Bone;
    ["N-TAN-Cheek_2_3L"]: THREE.Bone;
    ["N-TAN-Tail-Cheek_2_3L"]: THREE.Bone;
    ["N-TAN-NoseCrease_0L"]: THREE.Bone;
    ["N-BB-EyeLid_Crease_6L"]: THREE.Bone;
    ["N-TAN-NoseCrease_1L"]: THREE.Bone;
    ["N-TAN-Tail-NoseCrease_2L"]: THREE.Bone;
    ["N-TAN-Cheek_3_0L"]: THREE.Bone;
    ["N-BB-EyeLid_Crease_8L"]: THREE.Bone;
    ["N-TAN-Cheek_3_1L"]: THREE.Bone;
    ["N-TAN-Cheek_3_2L"]: THREE.Bone;
    ["N-BB-Cheek_3_2L"]: THREE.Bone;
    ["N-TAN-Cheek_Jawline_Across_3L"]: THREE.Bone;
    ["N-TAN-Tail-Cheek_Jawline_Across_3L"]: THREE.Bone;
    ["N-BB-EyeLid_Crease_10L"]: THREE.Bone;
    ["N-TAN-Cheek_5_1L"]: THREE.Bone;
    ["N-TAN-Cheek_5_2L"]: THREE.Bone;
    ["N-TAN-Tail-Cheek_5_2L"]: THREE.Bone;
    ["N-TAN-Cheek_4_2L"]: THREE.Bone;
    ["N-BB-Cheek_4_2L"]: THREE.Bone;
    ["N-TAN-Cheek_4_3L"]: THREE.Bone;
    ["N-TAN-Tail-Cheek_4_3L"]: THREE.Bone;
    ["N-TAN-Eyebrow_Lower_1L"]: THREE.Bone;
    ["N-TAN-Eyebrow_Lower_2L"]: THREE.Bone;
    ["N-TAN-Eyebrow_Lower_3L"]: THREE.Bone;
    ["N-TAN-Eyebrow_Lower_4L"]: THREE.Bone;
    ["N-TAN-Tail-Eyebrow_Lower_4L"]: THREE.Bone;
    ["N-BB-Lip_Bot_BotL"]: THREE.Bone;
    ["N-TAN-Lip_Bot_AcrossL"]: THREE.Bone;
    ["N-BB-Lip_Bot_TopL"]: THREE.Bone;
    ["N-TAN-Tail-Lip_Bot_AcrossL"]: THREE.Bone;
    ["N-TAN-EyeLid_Crease_4L"]: THREE.Bone;
    ["N-TAN-EyeLid_Crease_5L"]: THREE.Bone;
    ["N-TAN-EyeLid_Crease_6L"]: THREE.Bone;
    ["N-TAN-EyeLid_Crease_8L"]: THREE.Bone;
    ["N-TAN-EyeLid_Crease_10L"]: THREE.Bone;
    ["N-TAN-EyeLid_Crease_1L"]: THREE.Bone;
    ["N-TAN-EyeLid_Crease_2L"]: THREE.Bone;
    ["N-TAN-EyeLid_Crease_3L"]: THREE.Bone;
    ["N-TAN-NoseBridge_1_2L"]: THREE.Bone;
    ["N-TAN-NoseBridge_1_1L"]: THREE.Bone;
    ["N-TAN-Tail-NoseBridge_1_1L"]: THREE.Bone;
    ["N-BB-Chin_2L"]: THREE.Bone;
    ["N-TAN-Cheek_1_4L"]: THREE.Bone;
    ["N-BB-ChinM"]: THREE.Bone;
    ["N-TAN-Tail-Cheek_1_4L"]: THREE.Bone;
    ["N-BB-LaughLineM"]: THREE.Bone;
    ["N-TAN-LaughLine_5L"]: THREE.Bone;
    ["N-BB-LaughLine_7L"]: THREE.Bone;
    ["N-TAN-LaughLine_4L"]: THREE.Bone;
    ["N-BB-LaughLine_6L"]: THREE.Bone;
    ["N-TAN-LaughLine_3L"]: THREE.Bone;
    ["N-BB-LaughLine_5L"]: THREE.Bone;
    ["N-TAN-LaughLine_2L"]: THREE.Bone;
    ["N-BB-LaughLine_4L"]: THREE.Bone;
    ["N-TAN-LaughLine_1L"]: THREE.Bone;
    ["N-TAN-Tail-LaughLine_1L"]: THREE.Bone;
    ["N-BB-Lip_Bot_BotM"]: THREE.Bone;
    ["N-TAN-Lip_Bot_Bot_1L"]: THREE.Bone;
    ["N-TAN-Lip_Bot_Bot_2L"]: THREE.Bone;
    ["N-TAN-Lip_Bot_AcrossM"]: THREE.Bone;
    ["N-BB-Lip_Bot_TopM"]: THREE.Bone;
    ["N-TAN-Tail-Lip_Bot_AcrossM"]: THREE.Bone;
    ["N-TAN-Lip_Bot_Top_1L"]: THREE.Bone;
    ["N-TAN-Lip_Bot_Top_2L"]: THREE.Bone;
    ["N-TAN-Cheek_1_1L"]: THREE.Bone;
    ["N-BB-Cheek_1_1L"]: THREE.Bone;
    ["N-TAN-Cheek_1_2L"]: THREE.Bone;
    ["N-BB-Cheek_1_2L"]: THREE.Bone;
    ["N-TAN-Cheek_1_3L"]: THREE.Bone;
    ["N-TAN-Lip_Top_Top_1L"]: THREE.Bone;
    ["N-TAN-Tail-Lip_Top_Top_1L"]: THREE.Bone;
    ["N-TAN-Lip_Top_Bot_1L"]: THREE.Bone;
    ["N-TAN-Tail-Lip_Top_Bot_1L"]: THREE.Bone;
    ["N-TAN-LaughLine_Cheek_Across_1_1L"]: THREE.Bone;
    ["N-TAN-LaughLine_Cheek_Across_1_2L"]: THREE.Bone;
    ["N-TAN-LaughLine_Cheek_Across_2_1L"]: THREE.Bone;
    ["N-TAN-LaughLine_Cheek_Across_2_2L"]: THREE.Bone;
    ["N-TAN-Cheek_Cheek_Across_1L"]: THREE.Bone;
    ["N-TAN-Cheek_Cheek_Across_2L"]: THREE.Bone;
    ["N-TAN-Cheek_Jawline_AcrossL"]: THREE.Bone;
    ["N-TAN-Tail-Cheek_Jawline_AcrossL"]: THREE.Bone;
    ["N-BB-Lip_AboveM"]: THREE.Bone;
    ["N-TAN-NoseRing_1L"]: THREE.Bone;
    ["N-TAN-Nose_Lip_AcrossM"]: THREE.Bone;
    ["N-BB-Nostril_2L"]: THREE.Bone;
    ["N-TAN-NoseRing_2L"]: THREE.Bone;
    ["N-TAN-Tail-NoseMidLine_1L"]: THREE.Bone;
    ["N-TAN-Nose_Lip_AcrossL"]: THREE.Bone;
    ["N-BB-LaughLine_3R"]: THREE.Bone;
    ["N-TAN-NoseRing_3R"]: THREE.Bone;
    ["N-BB-LaughLine_2R"]: THREE.Bone;
    ["N-TAN-NoseRing_4R"]: THREE.Bone;
    ["N-BB-LaughLine_1R"]: THREE.Bone;
    ["N-TAN-NoseRing_5R"]: THREE.Bone;
    ["N-TAN-Tail-NoseRing_5R"]: THREE.Bone;
    ["N-TAN-NoseFront_1R"]: THREE.Bone;
    ["N-BB-Nostril_1R"]: THREE.Bone;
    ["N-TAN-NoseFront_2R"]: THREE.Bone;
    ["N-TAN-Tail-NoseFront_2R"]: THREE.Bone;
    ["N-BB-Forehead-_Top_1R"]: THREE.Bone;
    ["N-TAN-Forehead_2_2R"]: THREE.Bone;
    ["N-BB-Eyebrow_Top_1R"]: THREE.Bone;
    ["N-TAN-Eyebrow_Across_1R"]: THREE.Bone;
    ["N-BB-Eyebrow_Bot_1R"]: THREE.Bone;
    ["N-TAN-Brow_Crease_Across_2R"]: THREE.Bone;
    ["N-BB-EyeLid_Crease_2R"]: THREE.Bone;
    ["N-TAN-Crease_Lid_Across_2R"]: THREE.Bone;
    ["N-BB-Eyelid_Top_2R"]: THREE.Bone;
    ["N-TAN-Tail-Crease_Lid_Across_2R"]: THREE.Bone;
    ["N-BB-Forehead-_1R"]: THREE.Bone;
    ["N-TAN-Forehead_1_2R"]: THREE.Bone;
    ["N-BB-Eyebrow_1R"]: THREE.Bone;
    ["N-TAN-Brow_Crease_Across_1R"]: THREE.Bone;
    ["N-BB-EyeLid_Crease_1R"]: THREE.Bone;
    ["N-TAN-Crease_Lid_Across_1R"]: THREE.Bone;
    ["N-BB-Forehead-_Top_3R"]: THREE.Bone;
    ["N-TAN-Forehead_4_2R"]: THREE.Bone;
    ["N-BB-Eyebrow_Top_3R"]: THREE.Bone;
    ["N-TAN-Eyebrow_Across_3R"]: THREE.Bone;
    ["N-BB-Eyebrow_Bot_3R"]: THREE.Bone;
    ["N-TAN-FaceRing_1R"]: THREE.Bone;
    ["N-BB-NoseBridge_1R"]: THREE.Bone;
    ["N-TAN-FaceRing_2R"]: THREE.Bone;
    ["N-BB-NoseBridge_2R"]: THREE.Bone;
    ["N-TAN-FaceRing_3R"]: THREE.Bone;
    ["N-BB-Cheek_3_1R"]: THREE.Bone;
    ["N-TAN-FaceRing_6R"]: THREE.Bone;
    ["N-BB-Cheek_4_1R"]: THREE.Bone;
    ["N-TAN-FaceRing_7R"]: THREE.Bone;
    ["N-BB-Cheek_5_1R"]: THREE.Bone;
    ["N-TAN-FaceRing_8R"]: THREE.Bone;
    ["N-TAN-Eyebrow_Upper_1R"]: THREE.Bone;
    ["N-TAN-Eyebrow_Upper_2R"]: THREE.Bone;
    ["N-BB-Eyebrow_Top_2R"]: THREE.Bone;
    ["N-TAN-Eyebrow_Upper_3R"]: THREE.Bone;
    ["N-TAN-Eyebrow_Upper_4R"]: THREE.Bone;
    ["N-TAN-Tail-Eyebrow_Upper_4R"]: THREE.Bone;
    ["N-TAN-Brow_Crease_Across_4R"]: THREE.Bone;
    ["N-BB-EyeLid_Crease_4R"]: THREE.Bone;
    ["N-TAN-Crease_Lid_Across_4R"]: THREE.Bone;
    ["N-BB-Eyelid_Top_4R"]: THREE.Bone;
    ["N-TAN-Tail-Crease_Lid_Across_4R"]: THREE.Bone;
    ["N-BB-Forehead-_Top_2R"]: THREE.Bone;
    ["N-TAN-Forehead_3_2R"]: THREE.Bone;
    ["N-TAN-Eyebrow_Across_2R"]: THREE.Bone;
    ["N-BB-Eyebrow_Bot_2R"]: THREE.Bone;
    ["N-TAN-Brow_Crease_Across_3R"]: THREE.Bone;
    ["N-BB-EyeLid_Crease_3R"]: THREE.Bone;
    ["N-TAN-Crease_Lid_Across_3R"]: THREE.Bone;
    ["N-BB-Eyelid_Top_3R"]: THREE.Bone;
    ["N-TAN-Tail-Crease_Lid_Across_3R"]: THREE.Bone;
    ["N-BB-TempleR"]: THREE.Bone;
    ["N-TAN-Temple_2R"]: THREE.Bone;
    ["N-BB-JawLine_1R"]: THREE.Bone;
    ["N-TAN-JawLine_1R"]: THREE.Bone;
    ["N-BB-JawLine_2R"]: THREE.Bone;
    ["N-TAN-JawLine_2R"]: THREE.Bone;
    ["N-BB-JawLine_3R"]: THREE.Bone;
    ["N-TAN-JawLine_3R"]: THREE.Bone;
    ["N-BB-JawLine_4R"]: THREE.Bone;
    ["N-TAN-JawLine_4R"]: THREE.Bone;
    ["N-BB-JawLine_5R"]: THREE.Bone;
    ["N-TAN-JawLine_5R"]: THREE.Bone;
    ["N-TAN-Tail-JawLine_5R"]: THREE.Bone;
    ["N-TAN-Cheek_Jawline_Across_1R"]: THREE.Bone;
    ["N-TAN-Tail-Cheek_Jawline_Across_1R"]: THREE.Bone;
    ["N-TAN-Eyelid_Top_2R"]: THREE.Bone;
    ["N-TAN-Eyelid_Top_3R"]: THREE.Bone;
    ["N-TAN-Eyelid_Top_4R"]: THREE.Bone;
    ["N-BB-Eyelid_Top_5R"]: THREE.Bone;
    ["N-TAN-Tail-Eyelid_Top_4R"]: THREE.Bone;
    ["N-BB-Eyelid_Bot_2R"]: THREE.Bone;
    ["N-TAN-Eyelid_Bot_2R"]: THREE.Bone;
    ["N-BB-Eyelid_Bot_3R"]: THREE.Bone;
    ["N-TAN-Eyelid_Bot_3R"]: THREE.Bone;
    ["N-BB-Eyelid_Bot_4R"]: THREE.Bone;
    ["N-TAN-Eyelid_Bot_4R"]: THREE.Bone;
    ["N-BB-EyeLid_Crease_5R"]: THREE.Bone;
    ["N-TAN-NoseBridge_2_2R"]: THREE.Bone;
    ["N-TAN-NoseBridge_2_3R"]: THREE.Bone;
    ["N-TAN-Tail-NoseBridge_2_3R"]: THREE.Bone;
    ["N-TAN-NoseMidLine_3R"]: THREE.Bone;
    ["N-TAN-NoseMidLine_2R"]: THREE.Bone;
    ["N-TAN-NoseMidLine_1R"]: THREE.Bone;
    ["N-BB-Lip_Top_TopR"]: THREE.Bone;
    ["N-TAN-Lip_Top_AcrossR"]: THREE.Bone;
    ["N-BB-Lip_Top_BotR"]: THREE.Bone;
    ["N-TAN-Tail-Lip_Top_AcrossR"]: THREE.Bone;
    ["N-TAN-Cheek_2_0R"]: THREE.Bone;
    ["N-BB-Cheek_2_2R"]: THREE.Bone;
    ["N-TAN-Cheek_2_3R"]: THREE.Bone;
    ["N-TAN-Tail-Cheek_2_3R"]: THREE.Bone;
    ["N-TAN-NoseCrease_0R"]: THREE.Bone;
    ["N-TAN-Tail-NoseCrease_2R"]: THREE.Bone;
    ["N-TAN-Cheek_3_0R"]: THREE.Bone;
    ["N-BB-EyeLid_Crease_8R"]: THREE.Bone;
    ["N-TAN-Cheek_3_1R"]: THREE.Bone;
    ["N-TAN-Cheek_3_2R"]: THREE.Bone;
    ["N-BB-Cheek_3_2R"]: THREE.Bone;
    ["N-TAN-Cheek_Jawline_Across_3R"]: THREE.Bone;
    ["N-TAN-Tail-Cheek_Jawline_Across_3R"]: THREE.Bone;
    ["N-BB-EyeLid_Crease_10R"]: THREE.Bone;
    ["N-TAN-Cheek_5_1R"]: THREE.Bone;
    ["N-TAN-Cheek_5_2R"]: THREE.Bone;
    ["N-TAN-Tail-Cheek_5_2R"]: THREE.Bone;
    ["N-TAN-Cheek_4_2R"]: THREE.Bone;
    ["N-BB-Cheek_4_2R"]: THREE.Bone;
    ["N-TAN-Cheek_4_3R"]: THREE.Bone;
    ["N-TAN-Tail-Cheek_4_3R"]: THREE.Bone;
    ["N-TAN-Eyebrow_Lower_1R"]: THREE.Bone;
    ["N-TAN-Eyebrow_Lower_2R"]: THREE.Bone;
    ["N-TAN-Eyebrow_Lower_3R"]: THREE.Bone;
    ["N-TAN-Eyebrow_Lower_4R"]: THREE.Bone;
    ["N-TAN-Tail-Eyebrow_Lower_4R"]: THREE.Bone;
    ["N-BB-Lip_Bot_BotR"]: THREE.Bone;
    ["N-TAN-Lip_Bot_AcrossR"]: THREE.Bone;
    ["N-BB-Lip_Bot_TopR"]: THREE.Bone;
    ["N-TAN-Tail-Lip_Bot_AcrossR"]: THREE.Bone;
    ["N-TAN-EyeLid_Crease_4R"]: THREE.Bone;
    ["N-TAN-EyeLid_Crease_5R"]: THREE.Bone;
    ["N-TAN-EyeLid_Crease_8R"]: THREE.Bone;
    ["N-TAN-EyeLid_Crease_10R"]: THREE.Bone;
    ["N-TAN-EyeLid_Crease_1R"]: THREE.Bone;
    ["N-TAN-EyeLid_Crease_2R"]: THREE.Bone;
    ["N-TAN-EyeLid_Crease_3R"]: THREE.Bone;
    ["N-TAN-NoseBridge_1_2R"]: THREE.Bone;
    ["N-TAN-NoseBridge_1_1R"]: THREE.Bone;
    ["N-TAN-Tail-NoseBridge_1_1R"]: THREE.Bone;
    ["N-BB-Chin_2R"]: THREE.Bone;
    ["N-TAN-Cheek_1_4R"]: THREE.Bone;
    ["N-TAN-Tail-Cheek_1_4R"]: THREE.Bone;
    ["N-TAN-LaughLine_5R"]: THREE.Bone;
    ["N-BB-LaughLine_7R"]: THREE.Bone;
    ["N-TAN-LaughLine_4R"]: THREE.Bone;
    ["N-BB-LaughLine_6R"]: THREE.Bone;
    ["N-TAN-LaughLine_3R"]: THREE.Bone;
    ["N-BB-LaughLine_5R"]: THREE.Bone;
    ["N-TAN-LaughLine_2R"]: THREE.Bone;
    ["N-BB-LaughLine_4R"]: THREE.Bone;
    ["N-TAN-LaughLine_1R"]: THREE.Bone;
    ["N-TAN-Tail-LaughLine_1R"]: THREE.Bone;
    ["N-TAN-Lip_Bot_Bot_1R"]: THREE.Bone;
    ["N-TAN-Lip_Bot_Bot_2R"]: THREE.Bone;
    ["N-TAN-Lip_Bot_Top_1R"]: THREE.Bone;
    ["N-TAN-Lip_Bot_Top_2R"]: THREE.Bone;
    ["N-TAN-Cheek_1_1R"]: THREE.Bone;
    ["N-BB-Cheek_1_1R"]: THREE.Bone;
    ["N-TAN-Cheek_1_2R"]: THREE.Bone;
    ["N-BB-Cheek_1_2R"]: THREE.Bone;
    ["N-TAN-Cheek_1_3R"]: THREE.Bone;
    ["N-TAN-Lip_Top_Top_1R"]: THREE.Bone;
    ["N-TAN-Tail-Lip_Top_Top_1R"]: THREE.Bone;
    ["N-TAN-Lip_Top_Bot_1R"]: THREE.Bone;
    ["N-TAN-Tail-Lip_Top_Bot_1R"]: THREE.Bone;
    ["N-TAN-LaughLine_Cheek_Across_1_1R"]: THREE.Bone;
    ["N-TAN-LaughLine_Cheek_Across_1_2R"]: THREE.Bone;
    ["N-TAN-LaughLine_Cheek_Across_2_1R"]: THREE.Bone;
    ["N-TAN-LaughLine_Cheek_Across_2_2R"]: THREE.Bone;
    ["N-TAN-Cheek_Cheek_Across_1R"]: THREE.Bone;
    ["N-TAN-Cheek_Cheek_Across_2R"]: THREE.Bone;
    ["N-TAN-Cheek_Jawline_AcrossR"]: THREE.Bone;
    ["N-TAN-Tail-Cheek_Jawline_AcrossR"]: THREE.Bone;
    ["N-TAN-NoseRing_1R"]: THREE.Bone;
    ["N-BB-Nostril_2R"]: THREE.Bone;
    ["N-TAN-NoseRing_2R"]: THREE.Bone;
    ["N-TAN-Tail-NoseMidLine_1R"]: THREE.Bone;
    ["N-TAN-Nose_Lip_AcrossR"]: THREE.Bone;
    ["IK-P-Pole-ForearmL"]: THREE.Bone;
    ["IK-P-Hand_ParentL"]: THREE.Bone;
    ["MSTR-P-Foot_ParentL"]: THREE.Bone;
    ["IK-P-Pole-ForearmR"]: THREE.Bone;
    ["IK-P-Hand_ParentR"]: THREE.Bone;
    ["MSTR-P-Foot_ParentR"]: THREE.Bone;
  };
  materials: {
    ["MAT-rain.eyebrows"]: THREE.MeshStandardMaterial;
    ["MAT-rain.eyelashes"]: THREE.MeshStandardMaterial;
    ["MAT-rain.gums"]: THREE.MeshStandardMaterial;
    ["MAT-rain.teeth"]: THREE.MeshStandardMaterial;
    ["MAT-rain.tongue"]: THREE.MeshStandardMaterial;
    ["MAT-rain.body"]: THREE.MeshStandardMaterial;
    ["MAT-rain.hands"]: THREE.MeshStandardMaterial;
    ["Material.003"]: THREE.MeshStandardMaterial;
    ["MAT-rain.metal"]: THREE.MeshStandardMaterial;
    ["MAT-rain.socks"]: THREE.MeshStandardMaterial;
    ["MAT-rain.laces"]: THREE.MeshStandardMaterial;
    ["MAT-rain.top"]: THREE.MeshStandardMaterial;
    ["MAT-rain.eyes"]: THREE.MeshStandardMaterial;
    ["MAT-rain.head"]: THREE.MeshStandardMaterial;
    ["MAT-rain.hair"]: THREE.MeshStandardMaterial;
    ["MAT-rain.jeans"]: THREE.MeshStandardMaterial;
    ["Material.003"]: THREE.MeshStandardMaterial;
    ["Material.004"]: THREE.MeshStandardMaterial;
  };
};

type ActionName = "fingers" | "fingersOut" | "jump" | "jumpOut" | "kick" | "kickOut";
type GLTFActions = Record<ActionName, THREE.AnimationAction>;
const dict = ["fingers", "jump", "kick"];
export function Rain({ category = 0 , isMobile}: { category?: number, isMobile: boolean}) {
  const { characterCat, setCharacterCat, incrCharacterCat, decrCharacterCat } = useCharacterStore();
  // const [prevCategory, setPrevCategory] = useState<number | null>();
  const group = useRef<THREE.Group>(null);
  const { scrollYProgress } = useScroll();
  const lookat = new THREE.Vector3(0, isMobile ? 0.1 : 0.7, 0);
  const xposition = useTransform(scrollYProgress, [0, 1], [isMobile ? 1.5 : 2.9, isMobile ? -0.3 : -0.5]);
  const distance = useTransform(scrollYProgress, [0, 0.8], [0.5, 0.5]);
  const [prevCat, setPrevCat] = useState(null);

  const { nodes, materials, animations } = useGLTF("/rain_rig.glb") as GLTFResult;
  const { actions, mixer } = useAnimations(animations, group);



  // useEffect(() => {
  //   mixer.stopAllAction();

  //   mixer.addEventListener("finished", (e) => {
  //     console.log("finished");
  //     if (e.action._clip.name.endsWith("Out")) {
  //       mixer.stopAllAction();
  //       const action: string = dict[characterCat];
  //       if (!actions[action]) return;
  //       actions[action].reset();
  //       actions[action].clampWhenFinished = true;
  //       actions[action].setLoop(THREE.LoopOnce, 1).play();
  //       //       const action: string = dict[category];
  //       //       // console.log("finished", prevAction);
  //       //       mixer.stopAllAction();
  //       //       actions[action]?.reset().setLoop(THREE.LoopOnce, 1).play();
  //     }
  //   });
  //   //   // if (!actions["fingers"]) return;
  //   //   // actions["fingers"]?.play();
  // }, []);

  // useEffect(() => {
  //   mixer.stopAllAction();
  //   const action: string = dict[characterCat];
  //   if (!actions[action]) return;
  //   actions[action].reset();
  //   actions[action].clampWhenFinished = true;
  //   actions[action].setLoop(THREE.LoopOnce, 1).play();
  // }, []);

  // useEffect(() => {
  //   mixer.stopAllAction();
  //   const action: string = dict[prevCat] + "Out";

  //   actions[action]?.reset().setLoop(THREE.LoopOnce, 1).play();
  //   if (prevCat !== characterCat) {
  //     setPrevCat(characterCat);
  //   }
  //   mixer.addEventListener("finished", (e) => {
  //     console.log("finished");
  //     if (e.action._clip.name.endsWith("Out")) {
  //       mixer.stopAllAction();
  //       const action: string = dict[characterCat];
  //       actions[action]?.reset().setLoop(THREE.LoopOnce, 1).play();
  //       //       const action: string = dict[category];
  //       //       // console.log("finished", prevAction);
  //       //       mixer.stopAllAction();
  //       //       actions[action]?.reset().setLoop(THREE.LoopOnce, 1).play();
  //     }
  //   });
  // }, [characterCat]);

  useFrame(({ clock, camera }) => {
    // mixer.update(clock.getDelta());
    camera.position.y = xposition.get();
    camera.lookAt(lookat);
  });
  // useEffect(() => {
  //   if (!actions) return;
  //   console.log(actions);
  //   setPrevCategory(category);
  //   if (prevCategory) {
  //     const prevAction: string = dict[prevCategory] + "Out";
  //     mixer.stopAllAction();
  //     actions[prevAction]?.reset().setLoop(THREE.LoopOnce, 1).play();
  //   }
  // }, [category]);

  return (
    <group ref={group} dispose={null}>
      <group name="Scene">
        <group name="RIG-rain">
          <primitive object={nodes.TeethT} />
          <primitive object={nodes.TeethB} />
          <primitive object={nodes["P-BB-ChinM"]} />
          <primitive object={nodes["P-GRP-Lip_TopM"]} />
          <primitive object={nodes["P-BB-Chin_2L"]} />
          <primitive object={nodes["P-BB-LaughLineM"]} />
          <primitive object={nodes["P-BB-LaughLine_7L"]} />
          <primitive object={nodes["P-GRP-Lip_BotM"]} />
          <primitive object={nodes["FK-ToeL"]} />
          <primitive object={nodes["DEF-COR-Shin_TopL"]} />
          <primitive object={nodes["GRAB-HandL"]} />
          <primitive object={nodes["P-BB-JawLine_3L"]} />
          <primitive object={nodes["P-BB-Nose_3M"]} />
          <primitive object={nodes["P-BB-Cheek_SneerL"]} />
          <primitive object={nodes["P-BB-Cheek_3_2L"]} />
          <primitive object={nodes["P-BB-Cheek_2_2L"]} />
          <primitive object={nodes["P-BB-LaughLine_2L"]} />
          <primitive object={nodes["P-BB-Nostril_2L"]} />
          <primitive object={nodes["P-BB-Nostril_1L"]} />
          <primitive object={nodes["P-BB-LaughLine_1L"]} />
          <primitive object={nodes["P-BB-LaughLine_6L"]} />
          <primitive object={nodes["P-BB-LaughLine_4L"]} />
          <primitive object={nodes["P-BB-Cheek_2_1L"]} />
          <primitive object={nodes["P-BB-Cheek_3_1L"]} />
          <primitive object={nodes["P-BB-JawLine_2L"]} />
          <primitive object={nodes["P-BB-LaughLine_5L"]} />
          <primitive object={nodes["P-BB-Cheek_1_2L"]} />
          <primitive object={nodes["P-BB-Cheek_4_2L"]} />
          <primitive object={nodes["P-BB-Cheek_1_1L"]} />
          <primitive object={nodes["P-GRP-Nose_Front"]} />
          <primitive object={nodes["P-GRP-Lip_Top_1L"]} />
          <primitive object={nodes["P-GRP-Lip_Bot_1L"]} />
          <primitive object={nodes.Tongue_Root} />
          <primitive object={nodes["N-BB-Eyelid_Top_1L"]} />
          <primitive object={nodes["N-TAN-Tail-Crease_Lid_Across_1L"]} />
          <primitive object={nodes["N-BB-Cheek_SneerL"]} />
          <primitive object={nodes["N-TAN-FaceRing_4L"]} />
          <primitive object={nodes["N-BB-Cheek_2_1L"]} />
          <primitive object={nodes["N-TAN-FaceRing_5L"]} />
          <primitive object={nodes["N-BB-Eyelid_Bot_5L"]} />
          <primitive object={nodes["N-TAN-Cheek_4_0L"]} />
          <primitive object={nodes["N-BB-EyeLid_Crease_9L"]} />
          <primitive object={nodes["N-TAN-Cheek_4_1L"]} />
          <primitive object={nodes["N-TAN-Eyelid_Top_1L"]} />
          <primitive object={nodes["N-BB-Eyelid_Bot_1L"]} />
          <primitive object={nodes["N-TAN-Eyelid_Bot_1L"]} />
          <primitive object={nodes["N-TAN-Tail-Eyelid_Bot_4L"]} />
          <primitive object={nodes["N-BB-EyeLid_Crease_7L"]} />
          <primitive object={nodes["N-TAN-Cheek_2_1L"]} />
          <primitive object={nodes["N-TAN-Cheek_2_2L"]} />
          <primitive object={nodes["N-TAN-NoseCrease_2L"]} />
          <primitive object={nodes["N-TAN-EyeLid_Crease_7L"]} />
          <primitive object={nodes["N-TAN-EyeLid_Crease_9L"]} />
          <primitive object={nodes["N-BB-Lip_Bot_CornerL"]} />
          <primitive object={nodes["N-TAN-Tail-Lip_Bot_Bot_2L"]} />
          <primitive object={nodes["N-TAN-Tail-Lip_Bot_Top_2L"]} />
          <primitive object={nodes["N-BB-Lip_Top_CornerL"]} />
          <primitive object={nodes["N-TAN-Lip_Top_Top_2L"]} />
          <primitive object={nodes["N-TAN-Lip_Top_Bot_2L"]} />
          <primitive object={nodes["N-TAN-LaughLine_Lip_Across_1L"]} />
          <primitive object={nodes["N-TAN-Tail-LaughLine_Cheek_Across_1_2L"]} />
          <primitive object={nodes["N-TAN-LaughLine_Lip_Across_2L"]} />
          <primitive object={nodes.ROOT} />
          <primitive object={nodes["HNG-ThighL"]} />
          <primitive object={nodes["HNG-Upperarm_ParentL"]} />
          <primitive object={nodes["CTR-COR-Thumb_1L"]} />
          <primitive object={nodes["TGT-Eyes"]} />
          <primitive object={nodes["P-FK-Head"]} />
          <primitive object={nodes["P-GRP-Lip_Bot_2L"]} />
          <primitive object={nodes["P-GRP-Lip_Bot_2R"]} />
          <primitive object={nodes["P-GRP-Lip_Top_2L"]} />
          <primitive object={nodes["P-GRP-Lip_Top_2R"]} />
          <primitive object={nodes["P-ACT-Lips_CornerL"]} />
          <primitive object={nodes["P-ACT-Lips_CornerR"]} />
          <primitive object={nodes["P-BB-Cheek_4_1L"]} />
          <primitive object={nodes["P-BB-JawLine_1L"]} />
          <primitive object={nodes["P-GRP-NostrilL"]} />
          <primitive object={nodes["P-BB-Forehead-_TopM"]} />
          <primitive object={nodes["GRP-Nose_Bridge2"]} />
          <primitive object={nodes["P-BB-Forehead-_Top_1L"]} />
          <primitive object={nodes["P-BB-Forehead-_Top_3L"]} />
          <primitive object={nodes["P-BB-Forehead-_Top_2L"]} />
          <primitive object={nodes["P-BB-Forehead-_1L"]} />
          <primitive object={nodes["P-FK-Neck"]} />
          <primitive object={nodes["P-BB-Chin_2R"]} />
          <primitive object={nodes["P-BB-LaughLine_7R"]} />
          <primitive object={nodes["P-BB-JawLine_3R"]} />
          <primitive object={nodes["P-BB-Cheek_SneerR"]} />
          <primitive object={nodes["P-BB-Cheek_3_2R"]} />
          <primitive object={nodes["P-BB-Cheek_2_2R"]} />
          <primitive object={nodes["P-BB-LaughLine_2R"]} />
          <primitive object={nodes["P-BB-Nostril_2R"]} />
          <primitive object={nodes["P-BB-Nostril_1R"]} />
          <primitive object={nodes["P-BB-LaughLine_1R"]} />
          <primitive object={nodes["P-BB-LaughLine_6R"]} />
          <primitive object={nodes["P-BB-LaughLine_4R"]} />
          <primitive object={nodes["P-BB-Cheek_2_1R"]} />
          <primitive object={nodes["P-BB-Cheek_3_1R"]} />
          <primitive object={nodes["P-BB-JawLine_2R"]} />
          <primitive object={nodes["P-BB-LaughLine_5R"]} />
          <primitive object={nodes["P-BB-Cheek_1_2R"]} />
          <primitive object={nodes["P-BB-Cheek_4_2R"]} />
          <primitive object={nodes["P-BB-Cheek_1_1R"]} />
          <primitive object={nodes["P-GRP-Lip_Top_1R"]} />
          <primitive object={nodes["P-GRP-Lip_Bot_1R"]} />
          <primitive object={nodes["N-BB-Eyelid_Top_1R"]} />
          <primitive object={nodes["N-TAN-Tail-Crease_Lid_Across_1R"]} />
          <primitive object={nodes["N-BB-Cheek_SneerR"]} />
          <primitive object={nodes["N-TAN-FaceRing_4R"]} />
          <primitive object={nodes["N-BB-Cheek_2_1R"]} />
          <primitive object={nodes["N-TAN-FaceRing_5R"]} />
          <primitive object={nodes["N-BB-Eyelid_Bot_5R"]} />
          <primitive object={nodes["N-TAN-Cheek_4_0R"]} />
          <primitive object={nodes["N-BB-EyeLid_Crease_9R"]} />
          <primitive object={nodes["N-TAN-Cheek_4_1R"]} />
          <primitive object={nodes["N-TAN-Eyelid_Top_1R"]} />
          <primitive object={nodes["N-BB-Eyelid_Bot_1R"]} />
          <primitive object={nodes["N-TAN-Eyelid_Bot_1R"]} />
          <primitive object={nodes["N-TAN-Tail-Eyelid_Bot_4R"]} />
          <primitive object={nodes["N-BB-EyeLid_Crease_7R"]} />
          <primitive object={nodes["N-TAN-Cheek_2_1R"]} />
          <primitive object={nodes["N-TAN-Cheek_2_2R"]} />
          <primitive object={nodes["N-BB-EyeLid_Crease_6R"]} />
          <primitive object={nodes["N-TAN-NoseCrease_1R"]} />
          <primitive object={nodes["N-TAN-NoseCrease_2R"]} />
          <primitive object={nodes["N-TAN-EyeLid_Crease_6R"]} />
          <primitive object={nodes["N-TAN-EyeLid_Crease_7R"]} />
          <primitive object={nodes["N-TAN-EyeLid_Crease_9R"]} />
          <primitive object={nodes["N-BB-Lip_Bot_CornerR"]} />
          <primitive object={nodes["N-TAN-Tail-Lip_Bot_Bot_2R"]} />
          <primitive object={nodes["N-TAN-Tail-Lip_Bot_Top_2R"]} />
          <primitive object={nodes["N-BB-Lip_Top_CornerR"]} />
          <primitive object={nodes["N-TAN-Lip_Top_Top_2R"]} />
          <primitive object={nodes["N-TAN-Lip_Top_Bot_2R"]} />
          <primitive object={nodes["N-TAN-LaughLine_Lip_Across_1R"]} />
          <primitive object={nodes["N-TAN-Tail-LaughLine_Cheek_Across_1_2R"]} />
          <primitive object={nodes["N-TAN-LaughLine_Lip_Across_2R"]} />
          <primitive object={nodes["P-BB-Cheek_4_1R"]} />
          <primitive object={nodes["P-BB-JawLine_1R"]} />
          <primitive object={nodes["P-GRP-NostrilR"]} />
          <primitive object={nodes["P-BB-Forehead-_Top_1R"]} />
          <primitive object={nodes["P-BB-Forehead-_Top_3R"]} />
          <primitive object={nodes["P-BB-Forehead-_Top_2R"]} />
          <primitive object={nodes["P-BB-Forehead-_1R"]} />
          <primitive object={nodes["P-GRP-Nose_Bridge"]} />
          <primitive object={nodes["CTR-COR-Thumb_2L"]} />
          <primitive object={nodes["GRP-STR-Nose_Front"]} />
          <primitive object={nodes["GRP-STR-NostrilL"]} />
          <primitive object={nodes["GRP-STR-NostrilR"]} />
          <primitive object={nodes["P-SK-Cheek_PuffL"]} />
          <primitive object={nodes["P-SK-Cheek_PuffR"]} />
          <primitive object={nodes["FK-ToeR"]} />
          <primitive object={nodes["DEF-COR-Shin_TopR"]} />
          <primitive object={nodes["GRAB-HandR"]} />
          <primitive object={nodes["HNG-ThighR"]} />
          <primitive object={nodes["HNG-Upperarm_ParentR"]} />
          <primitive object={nodes["CTR-COR-Thumb_1R"]} />
          <primitive object={nodes["CTR-COR-Thumb_2R"]} />
          <primitive object={nodes.Root_EarL} />
          <primitive object={nodes.Root_EarR} />
          <primitive object={nodes["IK-P-Pole-ShinL"]} />
          <primitive object={nodes["IK-P-Pole-ShinR"]} />
          <primitive object={nodes["N-BB-Forehead-_TopM"]} />
          <primitive object={nodes["N-TAN-Forehead_2M"]} />
          <primitive object={nodes["N-BB-Eyebrow_TopM"]} />
          <primitive object={nodes["N-TAN-Eyebrow_AcrossM"]} />
          <primitive object={nodes["N-BB-Eyebrow_BotM"]} />
          <primitive object={nodes["N-TAN-Nose_1M"]} />
          <primitive object={nodes["N-BB-Nose_1M"]} />
          <primitive object={nodes["N-TAN-Nose_2M"]} />
          <primitive object={nodes["N-BB-Nose_2M"]} />
          <primitive object={nodes["N-TAN-Nose_3M"]} />
          <primitive object={nodes["N-BB-Nose_3M"]} />
          <primitive object={nodes["N-TAN-Nose_4M"]} />
          <primitive object={nodes["N-BB-Nose_4M"]} />
          <primitive object={nodes["N-TAN-Nose_5M"]} />
          <primitive object={nodes["N-BB-Lip_Top_TopM"]} />
          <primitive object={nodes["N-TAN-Lip_Top_AcrossM"]} />
          <primitive object={nodes["N-BB-Lip_Top_BotM"]} />
          <primitive object={nodes["N-TAN-Tail-Lip_Top_AcrossM"]} />
          <primitive object={nodes["N-BB-LaughLine_3L"]} />
          <primitive object={nodes["N-TAN-NoseRing_3L"]} />
          <primitive object={nodes["N-BB-LaughLine_2L"]} />
          <primitive object={nodes["N-TAN-NoseRing_4L"]} />
          <primitive object={nodes["N-BB-LaughLine_1L"]} />
          <primitive object={nodes["N-TAN-NoseRing_5L"]} />
          <primitive object={nodes["N-TAN-Tail-NoseRing_5L"]} />
          <primitive object={nodes["N-TAN-NoseFront_1L"]} />
          <primitive object={nodes["N-BB-Nostril_1L"]} />
          <primitive object={nodes["N-TAN-NoseFront_2L"]} />
          <primitive object={nodes["N-TAN-Tail-NoseFront_2L"]} />
          <primitive object={nodes["N-BB-Forehead-_Top_1L"]} />
          <primitive object={nodes["N-TAN-Forehead_2_2L"]} />
          <primitive object={nodes["N-BB-Eyebrow_Top_1L"]} />
          <primitive object={nodes["N-TAN-Eyebrow_Across_1L"]} />
          <primitive object={nodes["N-BB-Eyebrow_Bot_1L"]} />
          <primitive object={nodes["N-TAN-Brow_Crease_Across_2L"]} />
          <primitive object={nodes["N-BB-EyeLid_Crease_2L"]} />
          <primitive object={nodes["N-TAN-Crease_Lid_Across_2L"]} />
          <primitive object={nodes["N-BB-Eyelid_Top_2L"]} />
          <primitive object={nodes["N-TAN-Tail-Crease_Lid_Across_2L"]} />
          <primitive object={nodes["N-BB-Forehead-_1L"]} />
          <primitive object={nodes["N-TAN-Forehead_1_2L"]} />
          <primitive object={nodes["N-BB-Eyebrow_1L"]} />
          <primitive object={nodes["N-TAN-Brow_Crease_Across_1L"]} />
          <primitive object={nodes["N-BB-EyeLid_Crease_1L"]} />
          <primitive object={nodes["N-TAN-Crease_Lid_Across_1L"]} />
          <primitive object={nodes["N-BB-Forehead-_Top_3L"]} />
          <primitive object={nodes["N-TAN-Forehead_4_2L"]} />
          <primitive object={nodes["N-BB-Eyebrow_Top_3L"]} />
          <primitive object={nodes["N-TAN-Eyebrow_Across_3L"]} />
          <primitive object={nodes["N-BB-Eyebrow_Bot_3L"]} />
          <primitive object={nodes["N-TAN-FaceRing_1L"]} />
          <primitive object={nodes["N-BB-NoseBridge_1L"]} />
          <primitive object={nodes["N-TAN-FaceRing_2L"]} />
          <primitive object={nodes["N-BB-NoseBridge_2L"]} />
          <primitive object={nodes["N-TAN-FaceRing_3L"]} />
          <primitive object={nodes["N-BB-Cheek_3_1L"]} />
          <primitive object={nodes["N-TAN-FaceRing_6L"]} />
          <primitive object={nodes["N-BB-Cheek_4_1L"]} />
          <primitive object={nodes["N-TAN-FaceRing_7L"]} />
          <primitive object={nodes["N-BB-Cheek_5_1L"]} />
          <primitive object={nodes["N-TAN-FaceRing_8L"]} />
          <primitive object={nodes["N-TAN-Eyebrow_Upper_1L"]} />
          <primitive object={nodes["N-TAN-Eyebrow_Upper_2L"]} />
          <primitive object={nodes["N-BB-Eyebrow_Top_2L"]} />
          <primitive object={nodes["N-TAN-Eyebrow_Upper_3L"]} />
          <primitive object={nodes["N-TAN-Eyebrow_Upper_4L"]} />
          <primitive object={nodes["N-TAN-Tail-Eyebrow_Upper_4L"]} />
          <primitive object={nodes["N-TAN-Brow_Crease_Across_4L"]} />
          <primitive object={nodes["N-BB-EyeLid_Crease_4L"]} />
          <primitive object={nodes["N-TAN-Crease_Lid_Across_4L"]} />
          <primitive object={nodes["N-BB-Eyelid_Top_4L"]} />
          <primitive object={nodes["N-TAN-Tail-Crease_Lid_Across_4L"]} />
          <primitive object={nodes["N-BB-Forehead-_Top_2L"]} />
          <primitive object={nodes["N-TAN-Forehead_3_2L"]} />
          <primitive object={nodes["N-TAN-Eyebrow_Across_2L"]} />
          <primitive object={nodes["N-BB-Eyebrow_Bot_2L"]} />
          <primitive object={nodes["N-TAN-Brow_Crease_Across_3L"]} />
          <primitive object={nodes["N-BB-EyeLid_Crease_3L"]} />
          <primitive object={nodes["N-TAN-Crease_Lid_Across_3L"]} />
          <primitive object={nodes["N-BB-Eyelid_Top_3L"]} />
          <primitive object={nodes["N-TAN-Tail-Crease_Lid_Across_3L"]} />
          <primitive object={nodes["N-BB-TempleL"]} />
          <primitive object={nodes["N-TAN-Temple_2L"]} />
          <primitive object={nodes["N-BB-JawLine_1L"]} />
          <primitive object={nodes["N-TAN-JawLine_1L"]} />
          <primitive object={nodes["N-BB-JawLine_2L"]} />
          <primitive object={nodes["N-TAN-JawLine_2L"]} />
          <primitive object={nodes["N-BB-JawLine_3L"]} />
          <primitive object={nodes["N-TAN-JawLine_3L"]} />
          <primitive object={nodes["N-BB-JawLine_4L"]} />
          <primitive object={nodes["N-TAN-JawLine_4L"]} />
          <primitive object={nodes["N-BB-JawLine_5L"]} />
          <primitive object={nodes["N-TAN-JawLine_5L"]} />
          <primitive object={nodes["N-BB-JawLineM"]} />
          <primitive object={nodes["N-TAN-Tail-JawLine_5L"]} />
          <primitive object={nodes["N-TAN-Cheek_Jawline_Across_1L"]} />
          <primitive object={nodes["N-TAN-Tail-Cheek_Jawline_Across_1L"]} />
          <primitive object={nodes["N-TAN-Eyelid_Top_2L"]} />
          <primitive object={nodes["N-TAN-Eyelid_Top_3L"]} />
          <primitive object={nodes["N-TAN-Eyelid_Top_4L"]} />
          <primitive object={nodes["N-BB-Eyelid_Top_5L"]} />
          <primitive object={nodes["N-TAN-Tail-Eyelid_Top_4L"]} />
          <primitive object={nodes["N-BB-Eyelid_Bot_2L"]} />
          <primitive object={nodes["N-TAN-Eyelid_Bot_2L"]} />
          <primitive object={nodes["N-BB-Eyelid_Bot_3L"]} />
          <primitive object={nodes["N-TAN-Eyelid_Bot_3L"]} />
          <primitive object={nodes["N-BB-Eyelid_Bot_4L"]} />
          <primitive object={nodes["N-TAN-Eyelid_Bot_4L"]} />
          <primitive object={nodes["N-BB-EyeLid_Crease_5L"]} />
          <primitive object={nodes["N-TAN-NoseBridge_2_2L"]} />
          <primitive object={nodes["N-TAN-NoseBridge_2_3L"]} />
          <primitive object={nodes["N-TAN-Tail-NoseBridge_2_3L"]} />
          <primitive object={nodes["N-TAN-NoseMidLine_3L"]} />
          <primitive object={nodes["N-TAN-NoseMidLine_2L"]} />
          <primitive object={nodes["N-TAN-NoseMidLine_1L"]} />
          <primitive object={nodes["N-BB-Lip_Top_TopL"]} />
          <primitive object={nodes["N-TAN-Lip_Top_AcrossL"]} />
          <primitive object={nodes["N-BB-Lip_Top_BotL"]} />
          <primitive object={nodes["N-TAN-Tail-Lip_Top_AcrossL"]} />
          <primitive object={nodes["N-TAN-Cheek_2_0L"]} />
          <primitive object={nodes["N-BB-Cheek_2_2L"]} />
          <primitive object={nodes["N-TAN-Cheek_2_3L"]} />
          <primitive object={nodes["N-TAN-Tail-Cheek_2_3L"]} />
          <primitive object={nodes["N-TAN-NoseCrease_0L"]} />
          <primitive object={nodes["N-BB-EyeLid_Crease_6L"]} />
          <primitive object={nodes["N-TAN-NoseCrease_1L"]} />
          <primitive object={nodes["N-TAN-Tail-NoseCrease_2L"]} />
          <primitive object={nodes["N-TAN-Cheek_3_0L"]} />
          <primitive object={nodes["N-BB-EyeLid_Crease_8L"]} />
          <primitive object={nodes["N-TAN-Cheek_3_1L"]} />
          <primitive object={nodes["N-TAN-Cheek_3_2L"]} />
          <primitive object={nodes["N-BB-Cheek_3_2L"]} />
          <primitive object={nodes["N-TAN-Cheek_Jawline_Across_3L"]} />
          <primitive object={nodes["N-TAN-Tail-Cheek_Jawline_Across_3L"]} />
          <primitive object={nodes["N-BB-EyeLid_Crease_10L"]} />
          <primitive object={nodes["N-TAN-Cheek_5_1L"]} />
          <primitive object={nodes["N-TAN-Cheek_5_2L"]} />
          <primitive object={nodes["N-TAN-Tail-Cheek_5_2L"]} />
          <primitive object={nodes["N-TAN-Cheek_4_2L"]} />
          <primitive object={nodes["N-BB-Cheek_4_2L"]} />
          <primitive object={nodes["N-TAN-Cheek_4_3L"]} />
          <primitive object={nodes["N-TAN-Tail-Cheek_4_3L"]} />
          <primitive object={nodes["N-TAN-Eyebrow_Lower_1L"]} />
          <primitive object={nodes["N-TAN-Eyebrow_Lower_2L"]} />
          <primitive object={nodes["N-TAN-Eyebrow_Lower_3L"]} />
          <primitive object={nodes["N-TAN-Eyebrow_Lower_4L"]} />
          <primitive object={nodes["N-TAN-Tail-Eyebrow_Lower_4L"]} />
          <primitive object={nodes["N-BB-Lip_Bot_BotL"]} />
          <primitive object={nodes["N-TAN-Lip_Bot_AcrossL"]} />
          <primitive object={nodes["N-BB-Lip_Bot_TopL"]} />
          <primitive object={nodes["N-TAN-Tail-Lip_Bot_AcrossL"]} />
          <primitive object={nodes["N-TAN-EyeLid_Crease_4L"]} />
          <primitive object={nodes["N-TAN-EyeLid_Crease_5L"]} />
          <primitive object={nodes["N-TAN-EyeLid_Crease_6L"]} />
          <primitive object={nodes["N-TAN-EyeLid_Crease_8L"]} />
          <primitive object={nodes["N-TAN-EyeLid_Crease_10L"]} />
          <primitive object={nodes["N-TAN-EyeLid_Crease_1L"]} />
          <primitive object={nodes["N-TAN-EyeLid_Crease_2L"]} />
          <primitive object={nodes["N-TAN-EyeLid_Crease_3L"]} />
          <primitive object={nodes["N-TAN-NoseBridge_1_2L"]} />
          <primitive object={nodes["N-TAN-NoseBridge_1_1L"]} />
          <primitive object={nodes["N-TAN-Tail-NoseBridge_1_1L"]} />
          <primitive object={nodes["N-BB-Chin_2L"]} />
          <primitive object={nodes["N-TAN-Cheek_1_4L"]} />
          <primitive object={nodes["N-BB-ChinM"]} />
          <primitive object={nodes["N-TAN-Tail-Cheek_1_4L"]} />
          <primitive object={nodes["N-BB-LaughLineM"]} />
          <primitive object={nodes["N-TAN-LaughLine_5L"]} />
          <primitive object={nodes["N-BB-LaughLine_7L"]} />
          <primitive object={nodes["N-TAN-LaughLine_4L"]} />
          <primitive object={nodes["N-BB-LaughLine_6L"]} />
          <primitive object={nodes["N-TAN-LaughLine_3L"]} />
          <primitive object={nodes["N-BB-LaughLine_5L"]} />
          <primitive object={nodes["N-TAN-LaughLine_2L"]} />
          <primitive object={nodes["N-BB-LaughLine_4L"]} />
          <primitive object={nodes["N-TAN-LaughLine_1L"]} />
          <primitive object={nodes["N-TAN-Tail-LaughLine_1L"]} />
          <primitive object={nodes["N-BB-Lip_Bot_BotM"]} />
          <primitive object={nodes["N-TAN-Lip_Bot_Bot_1L"]} />
          <primitive object={nodes["N-TAN-Lip_Bot_Bot_2L"]} />
          <primitive object={nodes["N-TAN-Lip_Bot_AcrossM"]} />
          <primitive object={nodes["N-BB-Lip_Bot_TopM"]} />
          <primitive object={nodes["N-TAN-Tail-Lip_Bot_AcrossM"]} />
          <primitive object={nodes["N-TAN-Lip_Bot_Top_1L"]} />
          <primitive object={nodes["N-TAN-Lip_Bot_Top_2L"]} />
          <primitive object={nodes["N-TAN-Cheek_1_1L"]} />
          <primitive object={nodes["N-BB-Cheek_1_1L"]} />
          <primitive object={nodes["N-TAN-Cheek_1_2L"]} />
          <primitive object={nodes["N-BB-Cheek_1_2L"]} />
          <primitive object={nodes["N-TAN-Cheek_1_3L"]} />
          <primitive object={nodes["N-TAN-Lip_Top_Top_1L"]} />
          <primitive object={nodes["N-TAN-Tail-Lip_Top_Top_1L"]} />
          <primitive object={nodes["N-TAN-Lip_Top_Bot_1L"]} />
          <primitive object={nodes["N-TAN-Tail-Lip_Top_Bot_1L"]} />
          <primitive object={nodes["N-TAN-LaughLine_Cheek_Across_1_1L"]} />
          <primitive object={nodes["N-TAN-LaughLine_Cheek_Across_1_2L"]} />
          <primitive object={nodes["N-TAN-LaughLine_Cheek_Across_2_1L"]} />
          <primitive object={nodes["N-TAN-LaughLine_Cheek_Across_2_2L"]} />
          <primitive object={nodes["N-TAN-Cheek_Cheek_Across_1L"]} />
          <primitive object={nodes["N-TAN-Cheek_Cheek_Across_2L"]} />
          <primitive object={nodes["N-TAN-Cheek_Jawline_AcrossL"]} />
          <primitive object={nodes["N-TAN-Tail-Cheek_Jawline_AcrossL"]} />
          <primitive object={nodes["N-BB-Lip_AboveM"]} />
          <primitive object={nodes["N-TAN-NoseRing_1L"]} />
          <primitive object={nodes["N-TAN-Nose_Lip_AcrossM"]} />
          <primitive object={nodes["N-BB-Nostril_2L"]} />
          <primitive object={nodes["N-TAN-NoseRing_2L"]} />
          <primitive object={nodes["N-TAN-Tail-NoseMidLine_1L"]} />
          <primitive object={nodes["N-TAN-Nose_Lip_AcrossL"]} />
          <primitive object={nodes["N-BB-LaughLine_3R"]} />
          <primitive object={nodes["N-TAN-NoseRing_3R"]} />
          <primitive object={nodes["N-BB-LaughLine_2R"]} />
          <primitive object={nodes["N-TAN-NoseRing_4R"]} />
          <primitive object={nodes["N-BB-LaughLine_1R"]} />
          <primitive object={nodes["N-TAN-NoseRing_5R"]} />
          <primitive object={nodes["N-TAN-Tail-NoseRing_5R"]} />
          <primitive object={nodes["N-TAN-NoseFront_1R"]} />
          <primitive object={nodes["N-BB-Nostril_1R"]} />
          <primitive object={nodes["N-TAN-NoseFront_2R"]} />
          <primitive object={nodes["N-TAN-Tail-NoseFront_2R"]} />
          <primitive object={nodes["N-BB-Forehead-_Top_1R"]} />
          <primitive object={nodes["N-TAN-Forehead_2_2R"]} />
          <primitive object={nodes["N-BB-Eyebrow_Top_1R"]} />
          <primitive object={nodes["N-TAN-Eyebrow_Across_1R"]} />
          <primitive object={nodes["N-BB-Eyebrow_Bot_1R"]} />
          <primitive object={nodes["N-TAN-Brow_Crease_Across_2R"]} />
          <primitive object={nodes["N-BB-EyeLid_Crease_2R"]} />
          <primitive object={nodes["N-TAN-Crease_Lid_Across_2R"]} />
          <primitive object={nodes["N-BB-Eyelid_Top_2R"]} />
          <primitive object={nodes["N-TAN-Tail-Crease_Lid_Across_2R"]} />
          <primitive object={nodes["N-BB-Forehead-_1R"]} />
          <primitive object={nodes["N-TAN-Forehead_1_2R"]} />
          <primitive object={nodes["N-BB-Eyebrow_1R"]} />
          <primitive object={nodes["N-TAN-Brow_Crease_Across_1R"]} />
          <primitive object={nodes["N-BB-EyeLid_Crease_1R"]} />
          <primitive object={nodes["N-TAN-Crease_Lid_Across_1R"]} />
          <primitive object={nodes["N-BB-Forehead-_Top_3R"]} />
          <primitive object={nodes["N-TAN-Forehead_4_2R"]} />
          <primitive object={nodes["N-BB-Eyebrow_Top_3R"]} />
          <primitive object={nodes["N-TAN-Eyebrow_Across_3R"]} />
          <primitive object={nodes["N-BB-Eyebrow_Bot_3R"]} />
          <primitive object={nodes["N-TAN-FaceRing_1R"]} />
          <primitive object={nodes["N-BB-NoseBridge_1R"]} />
          <primitive object={nodes["N-TAN-FaceRing_2R"]} />
          <primitive object={nodes["N-BB-NoseBridge_2R"]} />
          <primitive object={nodes["N-TAN-FaceRing_3R"]} />
          <primitive object={nodes["N-BB-Cheek_3_1R"]} />
          <primitive object={nodes["N-TAN-FaceRing_6R"]} />
          <primitive object={nodes["N-BB-Cheek_4_1R"]} />
          <primitive object={nodes["N-TAN-FaceRing_7R"]} />
          <primitive object={nodes["N-BB-Cheek_5_1R"]} />
          <primitive object={nodes["N-TAN-FaceRing_8R"]} />
          <primitive object={nodes["N-TAN-Eyebrow_Upper_1R"]} />
          <primitive object={nodes["N-TAN-Eyebrow_Upper_2R"]} />
          <primitive object={nodes["N-BB-Eyebrow_Top_2R"]} />
          <primitive object={nodes["N-TAN-Eyebrow_Upper_3R"]} />
          <primitive object={nodes["N-TAN-Eyebrow_Upper_4R"]} />
          <primitive object={nodes["N-TAN-Tail-Eyebrow_Upper_4R"]} />
          <primitive object={nodes["N-TAN-Brow_Crease_Across_4R"]} />
          <primitive object={nodes["N-BB-EyeLid_Crease_4R"]} />
          <primitive object={nodes["N-TAN-Crease_Lid_Across_4R"]} />
          <primitive object={nodes["N-BB-Eyelid_Top_4R"]} />
          <primitive object={nodes["N-TAN-Tail-Crease_Lid_Across_4R"]} />
          <primitive object={nodes["N-BB-Forehead-_Top_2R"]} />
          <primitive object={nodes["N-TAN-Forehead_3_2R"]} />
          <primitive object={nodes["N-TAN-Eyebrow_Across_2R"]} />
          <primitive object={nodes["N-BB-Eyebrow_Bot_2R"]} />
          <primitive object={nodes["N-TAN-Brow_Crease_Across_3R"]} />
          <primitive object={nodes["N-BB-EyeLid_Crease_3R"]} />
          <primitive object={nodes["N-TAN-Crease_Lid_Across_3R"]} />
          <primitive object={nodes["N-BB-Eyelid_Top_3R"]} />
          <primitive object={nodes["N-TAN-Tail-Crease_Lid_Across_3R"]} />
          <primitive object={nodes["N-BB-TempleR"]} />
          <primitive object={nodes["N-TAN-Temple_2R"]} />
          <primitive object={nodes["N-BB-JawLine_1R"]} />
          <primitive object={nodes["N-TAN-JawLine_1R"]} />
          <primitive object={nodes["N-BB-JawLine_2R"]} />
          <primitive object={nodes["N-TAN-JawLine_2R"]} />
          <primitive object={nodes["N-BB-JawLine_3R"]} />
          <primitive object={nodes["N-TAN-JawLine_3R"]} />
          <primitive object={nodes["N-BB-JawLine_4R"]} />
          <primitive object={nodes["N-TAN-JawLine_4R"]} />
          <primitive object={nodes["N-BB-JawLine_5R"]} />
          <primitive object={nodes["N-TAN-JawLine_5R"]} />
          <primitive object={nodes["N-TAN-Tail-JawLine_5R"]} />
          <primitive object={nodes["N-TAN-Cheek_Jawline_Across_1R"]} />
          <primitive object={nodes["N-TAN-Tail-Cheek_Jawline_Across_1R"]} />
          <primitive object={nodes["N-TAN-Eyelid_Top_2R"]} />
          <primitive object={nodes["N-TAN-Eyelid_Top_3R"]} />
          <primitive object={nodes["N-TAN-Eyelid_Top_4R"]} />
          <primitive object={nodes["N-BB-Eyelid_Top_5R"]} />
          <primitive object={nodes["N-TAN-Tail-Eyelid_Top_4R"]} />
          <primitive object={nodes["N-BB-Eyelid_Bot_2R"]} />
          <primitive object={nodes["N-TAN-Eyelid_Bot_2R"]} />
          <primitive object={nodes["N-BB-Eyelid_Bot_3R"]} />
          <primitive object={nodes["N-TAN-Eyelid_Bot_3R"]} />
          <primitive object={nodes["N-BB-Eyelid_Bot_4R"]} />
          <primitive object={nodes["N-TAN-Eyelid_Bot_4R"]} />
          <primitive object={nodes["N-BB-EyeLid_Crease_5R"]} />
          <primitive object={nodes["N-TAN-NoseBridge_2_2R"]} />
          <primitive object={nodes["N-TAN-NoseBridge_2_3R"]} />
          <primitive object={nodes["N-TAN-Tail-NoseBridge_2_3R"]} />
          <primitive object={nodes["N-TAN-NoseMidLine_3R"]} />
          <primitive object={nodes["N-TAN-NoseMidLine_2R"]} />
          <primitive object={nodes["N-TAN-NoseMidLine_1R"]} />
          <primitive object={nodes["N-BB-Lip_Top_TopR"]} />
          <primitive object={nodes["N-TAN-Lip_Top_AcrossR"]} />
          <primitive object={nodes["N-BB-Lip_Top_BotR"]} />
          <primitive object={nodes["N-TAN-Tail-Lip_Top_AcrossR"]} />
          <primitive object={nodes["N-TAN-Cheek_2_0R"]} />
          <primitive object={nodes["N-BB-Cheek_2_2R"]} />
          <primitive object={nodes["N-TAN-Cheek_2_3R"]} />
          <primitive object={nodes["N-TAN-Tail-Cheek_2_3R"]} />
          <primitive object={nodes["N-TAN-NoseCrease_0R"]} />
          <primitive object={nodes["N-TAN-Tail-NoseCrease_2R"]} />
          <primitive object={nodes["N-TAN-Cheek_3_0R"]} />
          <primitive object={nodes["N-BB-EyeLid_Crease_8R"]} />
          <primitive object={nodes["N-TAN-Cheek_3_1R"]} />
          <primitive object={nodes["N-TAN-Cheek_3_2R"]} />
          <primitive object={nodes["N-BB-Cheek_3_2R"]} />
          <primitive object={nodes["N-TAN-Cheek_Jawline_Across_3R"]} />
          <primitive object={nodes["N-TAN-Tail-Cheek_Jawline_Across_3R"]} />
          <primitive object={nodes["N-BB-EyeLid_Crease_10R"]} />
          <primitive object={nodes["N-TAN-Cheek_5_1R"]} />
          <primitive object={nodes["N-TAN-Cheek_5_2R"]} />
          <primitive object={nodes["N-TAN-Tail-Cheek_5_2R"]} />
          <primitive object={nodes["N-TAN-Cheek_4_2R"]} />
          <primitive object={nodes["N-BB-Cheek_4_2R"]} />
          <primitive object={nodes["N-TAN-Cheek_4_3R"]} />
          <primitive object={nodes["N-TAN-Tail-Cheek_4_3R"]} />
          <primitive object={nodes["N-TAN-Eyebrow_Lower_1R"]} />
          <primitive object={nodes["N-TAN-Eyebrow_Lower_2R"]} />
          <primitive object={nodes["N-TAN-Eyebrow_Lower_3R"]} />
          <primitive object={nodes["N-TAN-Eyebrow_Lower_4R"]} />
          <primitive object={nodes["N-TAN-Tail-Eyebrow_Lower_4R"]} />
          <primitive object={nodes["N-BB-Lip_Bot_BotR"]} />
          <primitive object={nodes["N-TAN-Lip_Bot_AcrossR"]} />
          <primitive object={nodes["N-BB-Lip_Bot_TopR"]} />
          <primitive object={nodes["N-TAN-Tail-Lip_Bot_AcrossR"]} />
          <primitive object={nodes["N-TAN-EyeLid_Crease_4R"]} />
          <primitive object={nodes["N-TAN-EyeLid_Crease_5R"]} />
          <primitive object={nodes["N-TAN-EyeLid_Crease_8R"]} />
          <primitive object={nodes["N-TAN-EyeLid_Crease_10R"]} />
          <primitive object={nodes["N-TAN-EyeLid_Crease_1R"]} />
          <primitive object={nodes["N-TAN-EyeLid_Crease_2R"]} />
          <primitive object={nodes["N-TAN-EyeLid_Crease_3R"]} />
          <primitive object={nodes["N-TAN-NoseBridge_1_2R"]} />
          <primitive object={nodes["N-TAN-NoseBridge_1_1R"]} />
          <primitive object={nodes["N-TAN-Tail-NoseBridge_1_1R"]} />
          <primitive object={nodes["N-BB-Chin_2R"]} />
          <primitive object={nodes["N-TAN-Cheek_1_4R"]} />
          <primitive object={nodes["N-TAN-Tail-Cheek_1_4R"]} />
          <primitive object={nodes["N-TAN-LaughLine_5R"]} />
          <primitive object={nodes["N-BB-LaughLine_7R"]} />
          <primitive object={nodes["N-TAN-LaughLine_4R"]} />
          <primitive object={nodes["N-BB-LaughLine_6R"]} />
          <primitive object={nodes["N-TAN-LaughLine_3R"]} />
          <primitive object={nodes["N-BB-LaughLine_5R"]} />
          <primitive object={nodes["N-TAN-LaughLine_2R"]} />
          <primitive object={nodes["N-BB-LaughLine_4R"]} />
          <primitive object={nodes["N-TAN-LaughLine_1R"]} />
          <primitive object={nodes["N-TAN-Tail-LaughLine_1R"]} />
          <primitive object={nodes["N-TAN-Lip_Bot_Bot_1R"]} />
          <primitive object={nodes["N-TAN-Lip_Bot_Bot_2R"]} />
          <primitive object={nodes["N-TAN-Lip_Bot_Top_1R"]} />
          <primitive object={nodes["N-TAN-Lip_Bot_Top_2R"]} />
          <primitive object={nodes["N-TAN-Cheek_1_1R"]} />
          <primitive object={nodes["N-BB-Cheek_1_1R"]} />
          <primitive object={nodes["N-TAN-Cheek_1_2R"]} />
          <primitive object={nodes["N-BB-Cheek_1_2R"]} />
          <primitive object={nodes["N-TAN-Cheek_1_3R"]} />
          <primitive object={nodes["N-TAN-Lip_Top_Top_1R"]} />
          <primitive object={nodes["N-TAN-Tail-Lip_Top_Top_1R"]} />
          <primitive object={nodes["N-TAN-Lip_Top_Bot_1R"]} />
          <primitive object={nodes["N-TAN-Tail-Lip_Top_Bot_1R"]} />
          <primitive object={nodes["N-TAN-LaughLine_Cheek_Across_1_1R"]} />
          <primitive object={nodes["N-TAN-LaughLine_Cheek_Across_1_2R"]} />
          <primitive object={nodes["N-TAN-LaughLine_Cheek_Across_2_1R"]} />
          <primitive object={nodes["N-TAN-LaughLine_Cheek_Across_2_2R"]} />
          <primitive object={nodes["N-TAN-Cheek_Cheek_Across_1R"]} />
          <primitive object={nodes["N-TAN-Cheek_Cheek_Across_2R"]} />
          <primitive object={nodes["N-TAN-Cheek_Jawline_AcrossR"]} />
          <primitive object={nodes["N-TAN-Tail-Cheek_Jawline_AcrossR"]} />
          <primitive object={nodes["N-TAN-NoseRing_1R"]} />
          <primitive object={nodes["N-BB-Nostril_2R"]} />
          <primitive object={nodes["N-TAN-NoseRing_2R"]} />
          <primitive object={nodes["N-TAN-Tail-NoseMidLine_1R"]} />
          <primitive object={nodes["N-TAN-Nose_Lip_AcrossR"]} />
          <primitive object={nodes["IK-P-Pole-ForearmL"]} />
          <primitive object={nodes["IK-P-Hand_ParentL"]} />
          <primitive object={nodes["MSTR-P-Foot_ParentL"]} />
          <primitive object={nodes["IK-P-Pole-ForearmR"]} />
          <primitive object={nodes["IK-P-Hand_ParentR"]} />
          <primitive object={nodes["MSTR-P-Foot_ParentR"]} />
          <skinnedMesh
            castShadow
            name="GEO-rain_eyebrows"
            geometry={nodes["GEO-rain_eyebrows"].geometry}
            material={materials["MAT-rain.eyebrows"]}
            skeleton={nodes["GEO-rain_eyebrows"].skeleton}
          />
          <skinnedMesh
            castShadow
            name="GEO-rain_eyelashes"
            geometry={nodes["GEO-rain_eyelashes"].geometry}
            material={materials["MAT-rain.eyelashes"]}
            skeleton={nodes["GEO-rain_eyelashes"].skeleton}
          />
          <group name="GEO-rain_gums_lower">
            <skinnedMesh
              castShadow
              name="GEO-rain_gums_lower_Data"
              geometry={nodes["GEO-rain_gums_lower_Data"].geometry}
              material={materials["MAT-rain.gums"]}
              skeleton={nodes["GEO-rain_gums_lower_Data"].skeleton}
            />
            <skinnedMesh
              castShadow
              name="GEO-rain_gums_lower_Data_1"
              geometry={nodes["GEO-rain_gums_lower_Data_1"].geometry}
              material={materials["MAT-rain.teeth"]}
              skeleton={nodes["GEO-rain_gums_lower_Data_1"].skeleton}
            />
          </group>
          <group name="GEO-rain_gums_upper">
            <skinnedMesh
              castShadow
              name="GEO-rain_gums_upper_Data"
              geometry={nodes["GEO-rain_gums_upper_Data"].geometry}
              material={materials["MAT-rain.gums"]}
              skeleton={nodes["GEO-rain_gums_upper_Data"].skeleton}
            />
            <skinnedMesh
              castShadow
              name="GEO-rain_gums_upper_Data_1"
              geometry={nodes["GEO-rain_gums_upper_Data_1"].geometry}
              material={materials["MAT-rain.teeth"]}
              skeleton={nodes["GEO-rain_gums_upper_Data_1"].skeleton}
            />
          </group>
          <skinnedMesh
            castShadow
            name="GEO-rain_tongue"
            geometry={nodes["GEO-rain_tongue"].geometry}
            material={materials["MAT-rain.tongue"]}
            skeleton={nodes["GEO-rain_tongue"].skeleton}
          />
          <skinnedMesh
            castShadow
            name="GEO-rain_body"
            geometry={nodes["GEO-rain_body"].geometry}
            material={materials["MAT-rain.body"]}
            skeleton={nodes["GEO-rain_body"].skeleton}
          />
          <skinnedMesh
            castShadow
            name="GEO-rain_body001"
            geometry={nodes["GEO-rain_body001"].geometry}
            material={materials["MAT-rain.hands"]}
            skeleton={nodes["GEO-rain_body001"].skeleton}
          />
          <group name="GEO-rain_shoes">
            <skinnedMesh
              castShadow
              name="GEO-rain_shoes_Data"
              geometry={nodes["GEO-rain_shoes_Data"].geometry}
              material={materials["Material.003"]}
              skeleton={nodes["GEO-rain_shoes_Data"].skeleton}
            />
            <skinnedMesh
              castShadow
              name="GEO-rain_shoes_Data_1"
              geometry={nodes["GEO-rain_shoes_Data_1"].geometry}
              material={materials["MAT-rain.metal"]}
              skeleton={nodes["GEO-rain_shoes_Data_1"].skeleton}
            />
            <skinnedMesh
              castShadow
              name="GEO-rain_shoes_Data_2"
              geometry={nodes["GEO-rain_shoes_Data_2"].geometry}
              material={materials["MAT-rain.socks"]}
              skeleton={nodes["GEO-rain_shoes_Data_2"].skeleton}
            />
            <skinnedMesh
              castShadow
              name="GEO-rain_shoes_Data_3"
              geometry={nodes["GEO-rain_shoes_Data_3"].geometry}
              material={materials["MAT-rain.laces"]}
              skeleton={nodes["GEO-rain_shoes_Data_3"].skeleton}
            />
          </group>
          <skinnedMesh
            castShadow
            name="GEO-rain_top"
            geometry={nodes["GEO-rain_top"].geometry}
            material={materials["MAT-rain.top"]}
            skeleton={nodes["GEO-rain_top"].skeleton}
          />
          <skinnedMesh
            castShadow
            name="GEO-rain_eyes"
            geometry={nodes["GEO-rain_eyes"].geometry}
            material={materials["MAT-rain.eyes"]}
            skeleton={nodes["GEO-rain_eyes"].skeleton}
          />
          <skinnedMesh
            castShadow
            name="GEO-rain_head"
            geometry={nodes["GEO-rain_head"].geometry}
            material={materials["MAT-rain.head"]}
            skeleton={nodes["GEO-rain_head"].skeleton}
          />
          <skinnedMesh
            castShadow
            name="GEO-rain_hair_main"
            geometry={nodes["GEO-rain_hair_main"].geometry}
            material={materials["MAT-rain.hair"]}
            skeleton={nodes["GEO-rain_hair_main"].skeleton}
          />
          <skinnedMesh
            castShadow
            name="GEO-rain_hair_ponytail"
            geometry={nodes["GEO-rain_hair_ponytail"].geometry}
            material={materials["MAT-rain.hair"]}
            skeleton={nodes["GEO-rain_hair_ponytail"].skeleton}
          />
          <skinnedMesh
            castShadow
            name="GEO-rain_hair_strand"
            geometry={nodes["GEO-rain_hair_strand"].geometry}
            material={materials["MAT-rain.hair"]}
            skeleton={nodes["GEO-rain_hair_strand"].skeleton}
          />
          <skinnedMesh
            castShadow
            name="GEO-rain_jeans"
            geometry={nodes["GEO-rain_jeans"].geometry}
            material={materials["MAT-rain.jeans"]}
            skeleton={nodes["GEO-rain_jeans"].skeleton}
          />
        </group>
        {/* {!isMobile && (
          <Html
            fullscreen
            center
            receiveShadow
            zIndexRange={[-3, -4]}
            sprite={true}
            distanceFactor={2}
            position={new THREE.Vector3(0.5, 0, 0)}>
            <div className="w-full h-full screen-bg"></div>
          </Html>
        )} */}
        <PerspectiveCamera
          name="Camera_Orientation"
          position={[0, 0.3, isMobile ? 3.0 : 2.05]}
          makeDefault={true}
          far={1000}
          near={0.1}
          fov={60.28}
          rotation={[-Math.PI / 2, 0, 0]}
        />
        {/* <group name="Camera" position={[0, 0.91, -2.03]} rotation={[1.52, 0, 0]}> */}
        {/* <PerspectiveCamera
          name="Camera_Orientation"
          makeDefault={false}
          far={1000}
          near={0.1}
          fov={60.28}
          rotation={[-Math.PI / 2, 0, 0]}
          // position={new THREE.Vector3( 3, 10, 0.2)}
        /> */}
        {/* </group> */}
        {/* <mesh
          name="Cylinder"
          castShadow
          receiveShadow
          geometry={nodes.Cylinder.geometry}
          material={materials["Material.003"]}
          position={[0, -0.06, 0]}
          scale={[0.53, 0.09, 0.53]}
        />
        <mesh
          name="Cylinder001"
          castShadow
          receiveShadow
          geometry={nodes.Cylinder001.geometry}
          material={materials["Material.004"]}
          position={[0, 0.12, 0]}
          scale={[0.49, 0.08, 0.49]}
        /> */}
      </group>
    </group>
  );
}

useGLTF.preload("/rain_rig.glb");
