import Header from "@/components/header/Header";
import "./globals.css";
import { Inter } from "next/font/google";
import Footer from "@/components/footer/Footer";
import { Suspense } from "react";
import Loading from "./loading";
import Head from "next/head";
import { Metadata } from 'next';


const inter = Inter({ subsets: ["latin"] });

export const metadata:Metadata = {
  title: "Frontend developer & designer",
  description: "Generated by create next app",
  creator: "Swaggy Marie",
  
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  return (
    <html lang="en">
      <Head>
        <link rel="shortcut icon" href="/icon.png" />
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
      </Head>
      <body
        className={inter.className}
        style={{ height: "100vh" }}
      >
        <Header />
        <Suspense fallback={<Loading />}>{children}</Suspense>
        <Footer />
      </body>
    </html>
  );
}
