import Header from "@/components/header/Header";
import "./globals.css";
import { Inter } from "next/font/google";
import Footer from "@/components/footer/Footer";
import { Suspense } from "react";
import Loading from "./loading";
import Image from "next/image";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Frontend developer & designer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  let loadingScreen = true;
  let timeout = setTimeout(() => {
    loadingScreen = false;
  }, 6000);

  return (
    <html lang="en">
      <Head>
        <link rel="shortcut icon" href="/icon.png" />
      </Head>
      <body
        className={inter.className}
        style={{ height: loadingScreen ? "100vh" : "" }}
      >
        <Header />
        <Suspense fallback={<Loading />}>{children}</Suspense>
        <Footer />
      </body>
    </html>
  );
}
